//Auto-generated by https://github.com/pipe01/lcu-api-generator
using GlassLCU.API.Models;
using System.Threading.Tasks;
using static GlassLCU.API.GenerationUtils;
using System.Reflection;

namespace GlassLCU.API.Interfaces
{
    public static class LolActiveBoosts
    {
        /// <summary>
        /// <para>GET /lol-active-boosts/v1/active-boosts</para>
        /// </summary>
        [Endpoint("/lol-active-boosts/v1/active-boosts")]
        public static Task<LolActiveBoostsActiveBoosts> GetLolActiveBoostsV1ActiveBoosts()
            => Sender.Request<LolActiveBoostsActiveBoosts>("get", $"/lol-active-boosts/v1/active-boosts");

        public static string GetURL(string methodName)
        {
            return typeof(LolActiveBoosts).GetMethod(methodName).GetCustomAttribute<EndpointAttribute>().URL;
        }
    }
}
