//Auto-generated by https://github.com/pipe01/lcu-api-generator
using GlassLCU.API.Models;
using System.Threading.Tasks;
using static GlassLCU.API.GenerationUtils;
using System.Reflection;

namespace GlassLCU.API.Interfaces
{
    public static class LolCollections
    {
        /// <summary>
        /// <para>GET /lol-collections/v1/inventories/chest-eligibility</para>
        /// </summary>
        [Endpoint("/lol-collections/v1/inventories/chest-eligibility")]
        public static Task<LolCollectionsCollectionsChestEligibility> GetLolCollectionsV1InventoriesChestEligibility()
            => Sender.Request<LolCollectionsCollectionsChestEligibility>("get", $"/lol-collections/v1/inventories/chest-eligibility");
        /// <summary>
        /// <para>GET /lol-collections/v1/inventories/{summonerId}/backdrop</para>
        /// </summary>
        [Endpoint("/lol-collections/v1/inventories/{summonerId}/backdrop")]
        public static Task<LolCollectionsCollectionsSummonerBackdrop> GetLolCollectionsV1InventoriesBySummonerIdBackdrop([Parameter("summonerId", "path")] long summonerId)
            => Sender.Request<LolCollectionsCollectionsSummonerBackdrop>("get", $"/lol-collections/v1/inventories/{summonerId}/backdrop");
        /// <summary>
        /// <para>GET /lol-collections/v1/inventories/{summonerId}/champion-mastery</para>
        /// </summary>
        [Endpoint("/lol-collections/v1/inventories/{summonerId}/champion-mastery")]
        public static Task<LolCollectionsCollectionsChampionMastery[]> GetLolCollectionsV1InventoriesBySummonerIdChampionMastery([Parameter("summonerId", "path")] long summonerId)
            => Sender.Request<LolCollectionsCollectionsChampionMastery[]>("get", $"/lol-collections/v1/inventories/{summonerId}/champion-mastery");
        /// <summary>
        /// <para>GET /lol-collections/v1/inventories/{summonerId}/champion-mastery/top</para>
        /// </summary>
        [Endpoint("/lol-collections/v1/inventories/{summonerId}/champion-mastery/top")]
        public static Task<LolCollectionsCollectionsTopChampionMasteries> GetLolCollectionsV1InventoriesBySummonerIdChampionMasteryTop([Parameter("summonerId", "path")] long summonerId, [Parameter("limit", "query")] long limit, [Parameter("sortRule", "query")] string sortRule = default)
            => Sender.Request<LolCollectionsCollectionsTopChampionMasteries>("get", $"/lol-collections/v1/inventories/{summonerId}/champion-mastery/top?limit={System.Net.WebUtility.UrlEncode(limit.ToString())}&{(sortRule != default ? $"sortRule={System.Net.WebUtility.UrlEncode(sortRule.ToString())}" : null)}");
        /// <summary>
        /// <para>GET /lol-collections/v1/inventories/{summonerId}/rune-book</para>
        /// </summary>
        [Endpoint("/lol-collections/v1/inventories/{summonerId}/rune-book")]
        public static Task<LolCollectionsCollectionsRuneBook> GetLolCollectionsV1InventoriesBySummonerIdRuneBook([Parameter("summonerId", "path")] long summonerId)
            => Sender.Request<LolCollectionsCollectionsRuneBook>("get", $"/lol-collections/v1/inventories/{summonerId}/rune-book");
        /// <summary>
        /// <para>PUT /lol-collections/v1/inventories/{summonerId}/rune-book</para>
        /// </summary>
        [Endpoint("/lol-collections/v1/inventories/{summonerId}/rune-book")]
        public static Task<LolCollectionsCollectionsRuneBook> PutLolCollectionsV1InventoriesBySummonerIdRuneBook([Parameter("summonerId", "path")] long summonerId, [Parameter("resource", "body")] LolCollectionsCollectionsRuneBook resource)
            => Sender.Request<LolCollectionsCollectionsRuneBook>("put", $"/lol-collections/v1/inventories/{summonerId}/rune-book", resource);
        /// <summary>
        /// <para>PUT /lol-collections/v1/inventories/{summonerId}/rune-book/pages/{pageId}</para>
        /// </summary>
        [Endpoint("/lol-collections/v1/inventories/{summonerId}/rune-book/pages/{pageId}")]
        public static Task<LolCollectionsCollectionsRunePage> PutLolCollectionsV1InventoriesBySummonerIdRuneBookPagesByPageId([Parameter("summonerId", "path")] long summonerId, [Parameter("pageId", "path")] int pageId, [Parameter("resource", "body")] LolCollectionsCollectionsRunePage resource)
            => Sender.Request<LolCollectionsCollectionsRunePage>("put", $"/lol-collections/v1/inventories/{summonerId}/rune-book/pages/{pageId}", resource);
        /// <summary>
        /// <para>PUT /lol-collections/v1/inventories/{summonerId}/rune-book/select-page/{pageId}</para>
        /// </summary>
        [Endpoint("/lol-collections/v1/inventories/{summonerId}/rune-book/select-page/{pageId}")]
        public static Task<LolCollectionsCollectionsRunePage> PutLolCollectionsV1InventoriesBySummonerIdRuneBookSelectPageByPageId([Parameter("summonerId", "path")] long summonerId, [Parameter("pageId", "path")] int pageId)
            => Sender.Request<LolCollectionsCollectionsRunePage>("put", $"/lol-collections/v1/inventories/{summonerId}/rune-book/select-page/{pageId}");
        /// <summary>
        /// <para>GET /lol-collections/v1/inventories/{summonerId}/runes</para>
        /// </summary>
        [Endpoint("/lol-collections/v1/inventories/{summonerId}/runes")]
        public static Task<LolCollectionsCollectionsRuneQuantities> GetLolCollectionsV1InventoriesBySummonerIdRunes([Parameter("summonerId", "path")] long summonerId)
            => Sender.Request<LolCollectionsCollectionsRuneQuantities>("get", $"/lol-collections/v1/inventories/{summonerId}/runes");
        /// <summary>
        /// <para>GET /lol-collections/v1/inventories/{summonerId}/spells</para>
        /// </summary>
        [Endpoint("/lol-collections/v1/inventories/{summonerId}/spells")]
        public static Task<LolCollectionsCollectionsSummonerSpells> GetLolCollectionsV1InventoriesBySummonerIdSpells([Parameter("summonerId", "path")] long summonerId)
            => Sender.Request<LolCollectionsCollectionsSummonerSpells>("get", $"/lol-collections/v1/inventories/{summonerId}/spells");
        /// <summary>
        /// <para>GET /lol-collections/v1/inventories/{summonerId}/summoner-icons</para>
        /// </summary>
        [Endpoint("/lol-collections/v1/inventories/{summonerId}/summoner-icons")]
        public static Task<LolCollectionsCollectionsSummonerIcons> GetLolCollectionsV1InventoriesBySummonerIdSummonerIcons([Parameter("summonerId", "path")] long summonerId)
            => Sender.Request<LolCollectionsCollectionsSummonerIcons>("get", $"/lol-collections/v1/inventories/{summonerId}/summoner-icons");
        /// <summary>
        /// <para>PUT /lol-collections/v1/inventories/{summonerId}/verification</para>
        /// </summary>
        [Endpoint("/lol-collections/v1/inventories/{summonerId}/verification")]
        public static Task<string> PutLolCollectionsV1InventoriesBySummonerIdVerification([Parameter("summonerId", "path")] long summonerId, [Parameter("verificationCode", "body")] string verificationCode)
            => Sender.Request<string>("put", $"/lol-collections/v1/inventories/{summonerId}/verification", verificationCode);
        /// <summary>
        /// <para>GET /lol-collections/v1/inventories/{summonerId}/ward-skins</para>
        /// </summary>
        [Endpoint("/lol-collections/v1/inventories/{summonerId}/ward-skins")]
        public static Task<LolCollectionsCollectionsWardSkin[]> GetLolCollectionsV1InventoriesBySummonerIdWardSkins([Parameter("summonerId", "path")] long summonerId)
            => Sender.Request<LolCollectionsCollectionsWardSkin[]>("get", $"/lol-collections/v1/inventories/{summonerId}/ward-skins");
        /// <summary>
        /// <para>GET /lol-collections/v1/inventories/{summonerId}/ward-skins/{wardSkinId}</para>
        /// </summary>
        [Endpoint("/lol-collections/v1/inventories/{summonerId}/ward-skins/{wardSkinId}")]
        public static Task<LolCollectionsCollectionsWardSkin> GetLolCollectionsV1InventoriesBySummonerIdWardSkinsByWardSkinId([Parameter("summonerId", "path")] long summonerId, [Parameter("wardSkinId", "path")] long wardSkinId)
            => Sender.Request<LolCollectionsCollectionsWardSkin>("get", $"/lol-collections/v1/inventories/{summonerId}/ward-skins/{wardSkinId}");
        /// <summary>
        /// <para>GET /lol-collections/v2/inventories/{summonerId}/summoner-icons</para>
        /// </summary>
        [Endpoint("/lol-collections/v2/inventories/{summonerId}/summoner-icons")]
        public static Task<LolCollectionsCollectionsSummonerIcons> GetLolCollectionsV2InventoriesBySummonerIdSummonerIcons([Parameter("summonerId", "path")] long summonerId)
            => Sender.Request<LolCollectionsCollectionsSummonerIcons>("get", $"/lol-collections/v2/inventories/{summonerId}/summoner-icons");
        /// <summary>
        /// <para>GET /lol-collections/v2/inventories/{summonerId}/summoner-icons/{summonerIconId}</para>
        /// </summary>
        [Endpoint("/lol-collections/v2/inventories/{summonerId}/summoner-icons/{summonerIconId}")]
        public static Task<LolCollectionsCollectionsSummonerIcon> GetLolCollectionsV2InventoriesBySummonerIdSummonerIconsBySummonerIconId([Parameter("summonerId", "path")] long summonerId, [Parameter("summonerIconId", "path")] int summonerIconId)
            => Sender.Request<LolCollectionsCollectionsSummonerIcon>("get", $"/lol-collections/v2/inventories/{summonerId}/summoner-icons/{summonerIconId}");

        public static string GetURL(string methodName)
        {
            return typeof(LolCollections).GetMethod(methodName).GetCustomAttribute<EndpointAttribute>().URL;
        }
    }
}
