//Auto-generated by https://github.com/pipe01/lcu-api-generator
using GlassLCU.API.Models;
using System.Threading.Tasks;
using static GlassLCU.API.GenerationUtils;
using System.Reflection;

namespace GlassLCU.API.Interfaces
{
    public static class LolClubsPublic
    {
        /// <summary>
        /// <para>GET /lol-clubs-public/v1/clubs/public</para>
        /// </summary>
        [Endpoint("/lol-clubs-public/v1/clubs/public")]
        public static Task<LolClubsPublicClubsPublicData[]> GetLolClubsPublicV1ClubsPublic([Parameter("summonerNames", "query")] string summonerNames)
            => Sender.Request<LolClubsPublicClubsPublicData[]>("get", $"/lol-clubs-public/v1/clubs/public?summonerNames={System.Net.WebUtility.UrlEncode(summonerNames.ToString())}");
        /// <summary>
        /// <para>GET /lol-clubs-public/v1/clubs/public/{summonerId}</para>
        /// </summary>
        [Endpoint("/lol-clubs-public/v1/clubs/public/{summonerId}")]
        public static Task<LolClubsPublicClubsPublicData> GetLolClubsPublicV1ClubsPublicBySummonerId([Parameter("summonerId", "path")] long summonerId)
            => Sender.Request<LolClubsPublicClubsPublicData>("get", $"/lol-clubs-public/v1/clubs/public/{summonerId}");
        /// <summary>
        /// <para>GET /lol-clubs-public/v1/clubs/public/{summonerId}/tag</para>
        /// </summary>
        [Endpoint("/lol-clubs-public/v1/clubs/public/{summonerId}/tag")]
        public static Task<LolClubsPublicClubTag> GetLolClubsPublicV1ClubsPublicBySummonerIdTag([Parameter("summonerId", "path")] long summonerId)
            => Sender.Request<LolClubsPublicClubTag>("get", $"/lol-clubs-public/v1/clubs/public/{summonerId}/tag");

        public static string GetURL(string methodName)
        {
            return typeof(LolClubsPublic).GetMethod(methodName).GetCustomAttribute<EndpointAttribute>().URL;
        }
    }
}
