//Auto-generated by https://github.com/pipe01/lcu-api-generator
using GlassLCU.API.Models;
using System.Threading.Tasks;
using static GlassLCU.API.GenerationUtils;
using System.Reflection;

namespace GlassLCU.API.Interfaces
{
    public static class LolEndOfGame
    {
        /// <summary>
        /// <para>GET /lol-end-of-game/v1/champion-mastery-updates</para>
        /// </summary>
        [Endpoint("/lol-end-of-game/v1/champion-mastery-updates")]
        public static Task<LolEndOfGameChampionMasteryUpdate> GetLolEndOfGameV1ChampionMasteryUpdates()
            => Sender.Request<LolEndOfGameChampionMasteryUpdate>("get", $"/lol-end-of-game/v1/champion-mastery-updates");
        /// <summary>
        /// <para>GET /lol-end-of-game/v1/eog-stats-block</para>
        /// </summary>
        [Endpoint("/lol-end-of-game/v1/eog-stats-block")]
        public static Task<LolEndOfGameEndOfGameStats> GetLolEndOfGameV1EogStatsBlock()
            => Sender.Request<LolEndOfGameEndOfGameStats>("get", $"/lol-end-of-game/v1/eog-stats-block");
        /// <summary>
        /// <para>GET /lol-end-of-game/v1/reported-players</para>
        /// </summary>
        [Endpoint("/lol-end-of-game/v1/reported-players")]
        public static Task<long[]> GetLolEndOfGameV1ReportedPlayers()
            => Sender.Request<long[]>("get", $"/lol-end-of-game/v1/reported-players");
        /// <summary>
        /// <para>POST /lol-end-of-game/v1/state/dismiss-stats</para>
        /// </summary>
        [Endpoint("/lol-end-of-game/v1/state/dismiss-stats")]
        public static Task<object> PostLolEndOfGameV1StateDismissStats()
            => Sender.Request<object>("post", $"/lol-end-of-game/v1/state/dismiss-stats");
        /// <summary>
        /// <para>POST /lol-end-of-game/v2/player-complaints</para>
        /// </summary>
        [Endpoint("/lol-end-of-game/v2/player-complaints")]
        public static Task<LolEndOfGameEndOfGamePlayerComplaintV2> PostLolEndOfGameV2PlayerComplaints([Parameter("complaint", "body")] LolEndOfGameEndOfGamePlayerComplaintV2 complaint)
            => Sender.Request<LolEndOfGameEndOfGamePlayerComplaintV2>("post", $"/lol-end-of-game/v2/player-complaints", complaint);

        public static string GetURL(string methodName)
        {
            return typeof(LolEndOfGame).GetMethod(methodName).GetCustomAttribute<EndpointAttribute>().URL;
        }
    }
}
