//Auto-generated by https://github.com/pipe01/lcu-api-generator
using GlassLCU.API.Models;
using System.Threading.Tasks;
using static GlassLCU.API.GenerationUtils;
using System.Reflection;

namespace GlassLCU.API.Interfaces
{
    public static class LolGameSession
    {
        /// <summary>
        /// <para>GET /lol-game-session/v1/clearInfo</para>
        /// </summary>
        [Endpoint("/lol-game-session/v1/clearInfo")]
        public static Task GetLolGameSessionV1ClearInfo()
            => Sender.Request("get", $"/lol-game-session/v1/clearInfo");
        /// <summary>
        /// <para>GET /lol-game-session/v1/echo</para>
        /// </summary>
        [Endpoint("/lol-game-session/v1/echo")]
        public static Task<LolGameSessionGameSessionResult> GetLolGameSessionV1Echo()
            => Sender.Request<LolGameSessionGameSessionResult>("get", $"/lol-game-session/v1/echo");
        /// <summary>
        /// <para>GET /lol-game-session/v1/reconnectInfo</para>
        /// </summary>
        [Endpoint("/lol-game-session/v1/reconnectInfo")]
        public static Task<LolGameSessionGameSessionReconnect> GetLolGameSessionV1ReconnectInfo()
            => Sender.Request<LolGameSessionGameSessionReconnect>("get", $"/lol-game-session/v1/reconnectInfo");
        /// <summary>
        /// <para>GET /lol-game-session/v1/remote-echo</para>
        /// </summary>
        [Endpoint("/lol-game-session/v1/remote-echo")]
        public static Task<LolGameSessionGameSessionResult> GetLolGameSessionV1RemoteEcho([Parameter("message", "query")] string message)
            => Sender.Request<LolGameSessionGameSessionResult>("get", $"/lol-game-session/v1/remote-echo?message={System.Net.WebUtility.UrlEncode(message.ToString())}");

        public static string GetURL(string methodName)
        {
            return typeof(LolGameSession).GetMethod(methodName).GetCustomAttribute<EndpointAttribute>().URL;
        }
    }
}
