//Auto-generated by https://github.com/pipe01/lcu-api-generator
using GlassLCU.API.Models;
using System.Threading.Tasks;
using static GlassLCU.API.GenerationUtils;
using System.Reflection;

namespace GlassLCU.API.Interfaces
{
    public static class LolGameClientChat
    {
        /// <summary>
        /// <para>GET /lol-game-client-chat/v1/buddies</para>
        /// </summary>
        [Endpoint("/lol-game-client-chat/v1/buddies")]
        public static Task<string[]> GetLolGameClientChatV1Buddies()
            => Sender.Request<string[]>("get", $"/lol-game-client-chat/v1/buddies");
        /// <summary>
        /// <para>DELETE /lol-game-client-chat/v1/ignored-summoners</para>
        /// </summary>
        [Endpoint("/lol-game-client-chat/v1/ignored-summoners")]
        public static Task DeleteLolGameClientChatV1IgnoredSummoners([Parameter("summonerName", "query")] string summonerName)
            => Sender.Request("delete", $"/lol-game-client-chat/v1/ignored-summoners?summonerName={System.Net.WebUtility.UrlEncode(summonerName.ToString())}");
        /// <summary>
        /// <para>GET /lol-game-client-chat/v1/ignored-summoners</para>
        /// </summary>
        [Endpoint("/lol-game-client-chat/v1/ignored-summoners")]
        public static Task<string[]> GetLolGameClientChatV1IgnoredSummoners()
            => Sender.Request<string[]>("get", $"/lol-game-client-chat/v1/ignored-summoners");
        /// <summary>
        /// <para>POST /lol-game-client-chat/v1/ignored-summoners</para>
        /// </summary>
        [Endpoint("/lol-game-client-chat/v1/ignored-summoners")]
        public static Task PostLolGameClientChatV1IgnoredSummoners([Parameter("summonerName", "query")] string summonerName)
            => Sender.Request("post", $"/lol-game-client-chat/v1/ignored-summoners?summonerName={System.Net.WebUtility.UrlEncode(summonerName.ToString())}");
        /// <summary>
        /// <para>POST /lol-game-client-chat/v1/instant-messages</para>
        /// </summary>
        [Endpoint("/lol-game-client-chat/v1/instant-messages")]
        public static Task PostLolGameClientChatV1InstantMessages([Parameter("summonerName", "query")] string summonerName, [Parameter("message", "query")] string message)
            => Sender.Request("post", $"/lol-game-client-chat/v1/instant-messages?summonerName={System.Net.WebUtility.UrlEncode(summonerName.ToString())}&message={System.Net.WebUtility.UrlEncode(message.ToString())}");
        /// <summary>
        /// <para>POST /lol-game-client-chat/v1/party-messages</para>
        /// </summary>
        [Endpoint("/lol-game-client-chat/v1/party-messages")]
        public static Task PostLolGameClientChatV1PartyMessages([Parameter("message", "query")] string message)
            => Sender.Request("post", $"/lol-game-client-chat/v1/party-messages?message={System.Net.WebUtility.UrlEncode(message.ToString())}");

        public static string GetURL(string methodName)
        {
            return typeof(LolGameClientChat).GetMethod(methodName).GetCustomAttribute<EndpointAttribute>().URL;
        }
    }
}
