//Auto-generated by https://github.com/pipe01/lcu-api-generator
using GlassLCU.API.Models;
using System.Threading.Tasks;
using static GlassLCU.API.GenerationUtils;
using System.Reflection;

namespace GlassLCU.API.Interfaces
{
    public static class LolHighlights
    {
        /// <summary>
        /// <para>GET /lol-highlights/v1/config</para>
        /// </summary>
        [Endpoint("/lol-highlights/v1/config")]
        public static Task<LolHighlightsHighlightsConfig> GetLolHighlightsV1Config()
            => Sender.Request<LolHighlightsHighlightsConfig>("get", $"/lol-highlights/v1/config");
        /// <summary>
        /// <para>POST /lol-highlights/v1/file-browser/{highlightId}</para>
        /// </summary>
        [Endpoint("/lol-highlights/v1/file-browser/{highlightId}")]
        public static Task<object> PostLolHighlightsV1FileBrowserByHighlightId([Parameter("highlightId", "path")] long highlightId)
            => Sender.Request<object>("post", $"/lol-highlights/v1/file-browser/{highlightId}");
        /// <summary>
        /// <para>GET /lol-highlights/v1/highlights</para>
        /// </summary>
        [Endpoint("/lol-highlights/v1/highlights")]
        public static Task<LolHighlightsHighlight[]> GetLolHighlightsV1Highlights()
            => Sender.Request<LolHighlightsHighlight[]>("get", $"/lol-highlights/v1/highlights");
        /// <summary>
        /// <para>POST /lol-highlights/v1/highlights</para>
        /// </summary>
        [Endpoint("/lol-highlights/v1/highlights")]
        public static Task<LolHighlightsHighlight[]> PostLolHighlightsV1Highlights()
            => Sender.Request<LolHighlightsHighlight[]>("post", $"/lol-highlights/v1/highlights");
        /// <summary>
        /// <para>GET /lol-highlights/v1/highlights-folder-path</para>
        /// </summary>
        [Endpoint("/lol-highlights/v1/highlights-folder-path")]
        public static Task<string> GetLolHighlightsV1HighlightsFolderPath()
            => Sender.Request<string>("get", $"/lol-highlights/v1/highlights-folder-path");
        /// <summary>
        /// <para>GET /lol-highlights/v1/highlights-folder-path/default</para>
        /// </summary>
        [Endpoint("/lol-highlights/v1/highlights-folder-path/default")]
        public static Task<string> GetLolHighlightsV1HighlightsFolderPathDefault()
            => Sender.Request<string>("get", $"/lol-highlights/v1/highlights-folder-path/default");
        /// <summary>
        /// <para>DELETE /lol-highlights/v1/highlights/{id}</para>
        /// </summary>
        [Endpoint("/lol-highlights/v1/highlights/{id}")]
        public static Task<LolHighlightsHighlight> DeleteLolHighlightsV1HighlightsById([Parameter("id", "path")] long id)
            => Sender.Request<LolHighlightsHighlight>("delete", $"/lol-highlights/v1/highlights/{id}");
        /// <summary>
        /// <para>GET /lol-highlights/v1/highlights/{id}</para>
        /// </summary>
        [Endpoint("/lol-highlights/v1/highlights/{id}")]
        public static Task<LolHighlightsHighlight> GetLolHighlightsV1HighlightsById([Parameter("id", "path")] long id)
            => Sender.Request<LolHighlightsHighlight>("get", $"/lol-highlights/v1/highlights/{id}");
        /// <summary>
        /// <para>PUT /lol-highlights/v1/highlights/{id}</para>
        /// </summary>
        [Endpoint("/lol-highlights/v1/highlights/{id}")]
        public static Task<LolHighlightsHighlight> PutLolHighlightsV1HighlightsById([Parameter("id", "path")] long id, [Parameter("highlight", "body")] LolHighlightsHighlight highlight)
            => Sender.Request<LolHighlightsHighlight>("put", $"/lol-highlights/v1/highlights/{id}", highlight);

        public static string GetURL(string methodName)
        {
            return typeof(LolHighlights).GetMethod(methodName).GetCustomAttribute<EndpointAttribute>().URL;
        }
    }
}
