//Auto-generated by https://github.com/pipe01/lcu-api-generator
using GlassLCU.API.Models;
using System.Threading.Tasks;
using static GlassLCU.API.GenerationUtils;
using System.Reflection;

namespace GlassLCU.API.Interfaces
{
    public static class LolItemSets
    {
        /// <summary>
        /// <para>GET /lol-item-sets/v1/item-sets/{summonerId}/sets</para>
        /// </summary>
        [Endpoint("/lol-item-sets/v1/item-sets/{summonerId}/sets")]
        public static Task<LolItemSetsItemSets> GetLolItemSetsV1ItemSetsBySummonerIdSets([Parameter("summonerId", "path")] long summonerId)
            => Sender.Request<LolItemSetsItemSets>("get", $"/lol-item-sets/v1/item-sets/{summonerId}/sets");
        /// <summary>
        /// <para>POST /lol-item-sets/v1/item-sets/{summonerId}/sets</para>
        /// </summary>
        [Endpoint("/lol-item-sets/v1/item-sets/{summonerId}/sets")]
        public static Task PostLolItemSetsV1ItemSetsBySummonerIdSets([Parameter("summonerId", "path")] long summonerId, [Parameter("itemSet", "body")] LolItemSetsItemSet itemSet)
            => Sender.Request("post", $"/lol-item-sets/v1/item-sets/{summonerId}/sets", itemSet);
        /// <summary>
        /// <para>PUT /lol-item-sets/v1/item-sets/{summonerId}/sets</para>
        /// </summary>
        [Endpoint("/lol-item-sets/v1/item-sets/{summonerId}/sets")]
        public static Task PutLolItemSetsV1ItemSetsBySummonerIdSets([Parameter("summonerId", "path")] long summonerId, [Parameter("itemSets", "body")] LolItemSetsItemSets itemSets)
            => Sender.Request("put", $"/lol-item-sets/v1/item-sets/{summonerId}/sets", itemSets);

        public static string GetURL(string methodName)
        {
            return typeof(LolItemSets).GetMethod(methodName).GetCustomAttribute<EndpointAttribute>().URL;
        }
    }
}
