//Auto-generated by https://github.com/pipe01/lcu-api-generator
using GlassLCU.API.Models;
using System.Threading.Tasks;
using static GlassLCU.API.GenerationUtils;
using System.Reflection;

namespace GlassLCU.API.Interfaces
{
    public static class LolKrPlaytimeReminder
    {
        /// <summary>
        /// <para>GET /lol-kr-playtime-reminder/v1/message</para>
        /// </summary>
        [Endpoint("/lol-kr-playtime-reminder/v1/message")]
        public static Task<string> GetLolKrPlaytimeReminderV1Message()
            => Sender.Request<string>("get", $"/lol-kr-playtime-reminder/v1/message");
        /// <summary>
        /// <para>GET /lol-kr-playtime-reminder/v1/playtime</para>
        /// </summary>
        [Endpoint("/lol-kr-playtime-reminder/v1/playtime")]
        public static Task<LolKrPlaytimeReminderPlaytimeReminder> GetLolKrPlaytimeReminderV1Playtime()
            => Sender.Request<LolKrPlaytimeReminderPlaytimeReminder>("get", $"/lol-kr-playtime-reminder/v1/playtime");

        public static string GetURL(string methodName)
        {
            return typeof(LolKrPlaytimeReminder).GetMethod(methodName).GetCustomAttribute<EndpointAttribute>().URL;
        }
    }
}
