//Auto-generated by https://github.com/pipe01/lcu-api-generator
using GlassLCU.API.Models;
using System.Threading.Tasks;
using static GlassLCU.API.GenerationUtils;
using System.Reflection;

namespace GlassLCU.API.Interfaces
{
    public static class LolKrShutdownLaw
    {
        /// <summary>
        /// <para>GET /lol-kr-shutdown-law/v1/custom-status</para>
        /// </summary>
        [Endpoint("/lol-kr-shutdown-law/v1/custom-status")]
        public static Task<LolKrShutdownLawQueueShutdownStatus> GetLolKrShutdownLawV1CustomStatus()
            => Sender.Request<LolKrShutdownLawQueueShutdownStatus>("get", $"/lol-kr-shutdown-law/v1/custom-status");
        /// <summary>
        /// <para>GET /lol-kr-shutdown-law/v1/disabled-queues</para>
        /// </summary>
        [Endpoint("/lol-kr-shutdown-law/v1/disabled-queues")]
        public static Task<int[]> GetLolKrShutdownLawV1DisabledQueues()
            => Sender.Request<int[]>("get", $"/lol-kr-shutdown-law/v1/disabled-queues");
        /// <summary>
        /// <para>GET /lol-kr-shutdown-law/v1/notification</para>
        /// </summary>
        [Endpoint("/lol-kr-shutdown-law/v1/notification")]
        public static Task<LolKrShutdownLawShutdownLawNotification> GetLolKrShutdownLawV1Notification()
            => Sender.Request<LolKrShutdownLawShutdownLawNotification>("get", $"/lol-kr-shutdown-law/v1/notification");
        /// <summary>
        /// <para>GET /lol-kr-shutdown-law/v1/queue-status/{queue_id}</para>
        /// </summary>
        [Endpoint("/lol-kr-shutdown-law/v1/queue-status/{queue_id}")]
        public static Task<LolKrShutdownLawQueueShutdownStatus> GetLolKrShutdownLawV1QueueStatusByQueueId([Parameter("queue_id", "path")] int queue_id)
            => Sender.Request<LolKrShutdownLawQueueShutdownStatus>("get", $"/lol-kr-shutdown-law/v1/queue-status/{queue_id}");
        /// <summary>
        /// <para>GET /lol-kr-shutdown-law/v1/status</para>
        /// </summary>
        [Endpoint("/lol-kr-shutdown-law/v1/status")]
        public static Task<LolKrShutdownLawAllQueueShutdownStatus> GetLolKrShutdownLawV1Status()
            => Sender.Request<LolKrShutdownLawAllQueueShutdownStatus>("get", $"/lol-kr-shutdown-law/v1/status");

        public static string GetURL(string methodName)
        {
            return typeof(LolKrShutdownLaw).GetMethod(methodName).GetCustomAttribute<EndpointAttribute>().URL;
        }
    }
}
