//Auto-generated by https://github.com/pipe01/lcu-api-generator
using GlassLCU.API.Models;
using System.Threading.Tasks;
using static GlassLCU.API.GenerationUtils;
using System.Reflection;

namespace GlassLCU.API.Interfaces
{
    public static class LolLeaverBuster
    {
        /// <summary>
        /// <para>GET /lol-leaver-buster/v1/notifications</para>
        /// </summary>
        [Endpoint("/lol-leaver-buster/v1/notifications")]
        public static Task<LolLeaverBusterLeaverBusterNotificationResource[]> GetLolLeaverBusterV1Notifications()
            => Sender.Request<LolLeaverBusterLeaverBusterNotificationResource[]>("get", $"/lol-leaver-buster/v1/notifications");
        /// <summary>
        /// <para>DELETE /lol-leaver-buster/v1/notifications/{id}</para>
        /// </summary>
        [Endpoint("/lol-leaver-buster/v1/notifications/{id}")]
        public static Task<object> DeleteLolLeaverBusterV1NotificationsById([Parameter("id", "path")] int id)
            => Sender.Request<object>("delete", $"/lol-leaver-buster/v1/notifications/{id}");
        /// <summary>
        /// <para>GET /lol-leaver-buster/v1/notifications/{id}</para>
        /// </summary>
        [Endpoint("/lol-leaver-buster/v1/notifications/{id}")]
        public static Task<LolLeaverBusterLeaverBusterNotificationResource> GetLolLeaverBusterV1NotificationsById([Parameter("id", "path")] int id)
            => Sender.Request<LolLeaverBusterLeaverBusterNotificationResource>("get", $"/lol-leaver-buster/v1/notifications/{id}");

        public static string GetURL(string methodName)
        {
            return typeof(LolLeaverBuster).GetMethod(methodName).GetCustomAttribute<EndpointAttribute>().URL;
        }
    }
}
