//Auto-generated by https://github.com/pipe01/lcu-api-generator
using GlassLCU.API.Models;
using System.Threading.Tasks;
using static GlassLCU.API.GenerationUtils;
using System.Reflection;

namespace GlassLCU.API.Interfaces
{
    public static class LolMissions
    {
        /// <summary>
        /// <para>GET /lol-missions/v1/data</para>
        /// </summary>
        [Endpoint("/lol-missions/v1/data")]
        public static Task<PlayerMissionEligibilityData> GetLolMissionsV1Data()
            => Sender.Request<PlayerMissionEligibilityData>("get", $"/lol-missions/v1/data");
        /// <summary>
        /// <para>POST /lol-missions/v1/force</para>
        /// </summary>
        [Endpoint("/lol-missions/v1/force")]
        public static Task PostLolMissionsV1Force()
            => Sender.Request("post", $"/lol-missions/v1/force");
        /// <summary>
        /// <para>GET /lol-missions/v1/missions</para>
        /// </summary>
        [Endpoint("/lol-missions/v1/missions")]
        public static Task<PlayerMissionDTO[]> GetLolMissionsV1Missions()
            => Sender.Request<PlayerMissionDTO[]>("get", $"/lol-missions/v1/missions");
        /// <summary>
        /// <para>PATCH /lol-missions/v1/player</para>
        /// </summary>
        [Endpoint("/lol-missions/v1/player")]
        public static Task PatchLolMissionsV1Player([Parameter("seriesOpt", "body")] LolMissionsSeriesOpt seriesOpt)
            => Sender.Request("patch", $"/lol-missions/v1/player", seriesOpt);
        /// <summary>
        /// <para>PUT /lol-missions/v1/player</para>
        /// </summary>
        [Endpoint("/lol-missions/v1/player")]
        public static Task PutLolMissionsV1Player([Parameter("ids", "body")] IdsDTO ids)
            => Sender.Request("put", $"/lol-missions/v1/player", ids);
        /// <summary>
        /// <para>PUT /lol-missions/v1/player/opt</para>
        /// </summary>
        [Endpoint("/lol-missions/v1/player/opt")]
        public static Task PutLolMissionsV1PlayerOpt([Parameter("seriesOpts", "body")] object seriesOpts)
            => Sender.Request("put", $"/lol-missions/v1/player/opt", seriesOpts);
        /// <summary>
        /// <para>PUT /lol-missions/v1/player/{missionId}</para>
        /// </summary>
        [Endpoint("/lol-missions/v1/player/{missionId}")]
        public static Task PutLolMissionsV1PlayerByMissionId([Parameter("missionId", "path")] string missionId, [Parameter("rewardGroups", "body")] LolMissionsRewardGroupsSelection rewardGroups)
            => Sender.Request("put", $"/lol-missions/v1/player/{missionId}", rewardGroups);
        /// <summary>
        /// <para>GET /lol-missions/v1/series</para>
        /// </summary>
        [Endpoint("/lol-missions/v1/series")]
        public static Task<SeriesDTO[]> GetLolMissionsV1Series()
            => Sender.Request<SeriesDTO[]>("get", $"/lol-missions/v1/series");

        public static string GetURL(string methodName)
        {
            return typeof(LolMissions).GetMethod(methodName).GetCustomAttribute<EndpointAttribute>().URL;
        }
    }
}
