//Auto-generated by https://github.com/pipe01/lcu-api-generator
using GlassLCU.API.Models;
using System.Threading.Tasks;
using static GlassLCU.API.GenerationUtils;
using System.Reflection;

namespace GlassLCU.API.Interfaces
{
    public static class LolMaps
    {
        /// <summary>
        /// <para>POST /lol-maps/v1/map</para>
        /// </summary>
        [Endpoint("/lol-maps/v1/map")]
        public static Task PostLolMapsV1Map([Parameter("map", "body")] LolMapsMaps map)
            => Sender.Request("post", $"/lol-maps/v1/map", map);
        /// <summary>
        /// <para>GET /lol-maps/v1/map/{id}</para>
        /// </summary>
        [Endpoint("/lol-maps/v1/map/{id}")]
        public static Task<LolMapsMaps> GetLolMapsV1MapById([Parameter("id", "path")] long id)
            => Sender.Request<LolMapsMaps>("get", $"/lol-maps/v1/map/{id}");
        /// <summary>
        /// <para>GET /lol-maps/v1/maps</para>
        /// </summary>
        [Endpoint("/lol-maps/v1/maps")]
        public static Task<LolMapsMaps[]> GetLolMapsV1Maps()
            => Sender.Request<LolMapsMaps[]>("get", $"/lol-maps/v1/maps");
        /// <summary>
        /// <para>GET /lol-maps/v2/map/{id}/{gameMode}</para>
        /// </summary>
        [Endpoint("/lol-maps/v2/map/{id}/{gameMode}")]
        public static Task<LolMapsMaps> GetLolMapsV2MapByIdByGameMode([Parameter("id", "path")] long id, [Parameter("gameMode", "path")] string gameMode)
            => Sender.Request<LolMapsMaps>("get", $"/lol-maps/v2/map/{id}/{gameMode}");
        /// <summary>
        /// <para>GET /lol-maps/v2/map/{id}/{gameMode}/{gameMutator}</para>
        /// </summary>
        [Endpoint("/lol-maps/v2/map/{id}/{gameMode}/{gameMutator}")]
        public static Task<LolMapsMaps> GetLolMapsV2MapByIdByGameModeByGameMutator([Parameter("id", "path")] long id, [Parameter("gameMode", "path")] string gameMode, [Parameter("gameMutator", "path")] string gameMutator)
            => Sender.Request<LolMapsMaps>("get", $"/lol-maps/v2/map/{id}/{gameMode}/{gameMutator}");
        /// <summary>
        /// <para>GET /lol-maps/v2/maps</para>
        /// </summary>
        [Endpoint("/lol-maps/v2/maps")]
        public static Task<LolMapsMaps[]> GetLolMapsV2Maps()
            => Sender.Request<LolMapsMaps[]>("get", $"/lol-maps/v2/maps");

        public static string GetURL(string methodName)
        {
            return typeof(LolMaps).GetMethod(methodName).GetCustomAttribute<EndpointAttribute>().URL;
        }
    }
}
