//Auto-generated by https://github.com/pipe01/lcu-api-generator
using GlassLCU.API.Models;
using System.Threading.Tasks;
using static GlassLCU.API.GenerationUtils;
using System.Reflection;

namespace GlassLCU.API.Interfaces
{
    public static class LolNpeRewards
    {
        /// <summary>
        /// <para>POST /lol-npe-rewards/v1/fetch-rewards</para>
        /// </summary>
        [Endpoint("/lol-npe-rewards/v1/fetch-rewards")]
        public static Task PostLolNpeRewardsV1FetchRewards()
            => Sender.Request("post", $"/lol-npe-rewards/v1/fetch-rewards");
        /// <summary>
        /// <para>GET /lol-npe-rewards/v1/level-rewards</para>
        /// </summary>
        [Endpoint("/lol-npe-rewards/v1/level-rewards")]
        public static Task<LolNpeRewardsRewardSeries> GetLolNpeRewardsV1LevelRewards()
            => Sender.Request<LolNpeRewardsRewardSeries>("get", $"/lol-npe-rewards/v1/level-rewards");
        /// <summary>
        /// <para>GET /lol-npe-rewards/v1/level-rewards/state</para>
        /// </summary>
        [Endpoint("/lol-npe-rewards/v1/level-rewards/state")]
        public static Task<LolNpeRewardsRewardSeriesState> GetLolNpeRewardsV1LevelRewardsState()
            => Sender.Request<LolNpeRewardsRewardSeriesState>("get", $"/lol-npe-rewards/v1/level-rewards/state");
        /// <summary>
        /// <para>GET /lol-npe-rewards/v1/login-rewards</para>
        /// </summary>
        [Endpoint("/lol-npe-rewards/v1/login-rewards")]
        public static Task<LolNpeRewardsRewardSeries> GetLolNpeRewardsV1LoginRewards()
            => Sender.Request<LolNpeRewardsRewardSeries>("get", $"/lol-npe-rewards/v1/login-rewards");
        /// <summary>
        /// <para>GET /lol-npe-rewards/v1/login-rewards/state</para>
        /// </summary>
        [Endpoint("/lol-npe-rewards/v1/login-rewards/state")]
        public static Task<LolNpeRewardsRewardSeriesState> GetLolNpeRewardsV1LoginRewardsState()
            => Sender.Request<LolNpeRewardsRewardSeriesState>("get", $"/lol-npe-rewards/v1/login-rewards/state");

        public static string GetURL(string methodName)
        {
            return typeof(LolNpeRewards).GetMethod(methodName).GetCustomAttribute<EndpointAttribute>().URL;
        }
    }
}
