//Auto-generated by https://github.com/pipe01/lcu-api-generator
using GlassLCU.API.Models;
using System.Threading.Tasks;
using static GlassLCU.API.GenerationUtils;
using System.Reflection;

namespace GlassLCU.API.Interfaces
{
    public static class LolNpeTutorialPath
    {
        /// <summary>
        /// <para>GET /lol-npe-tutorial-path/v1/how-to-win-stats</para>
        /// </summary>
        [Endpoint("/lol-npe-tutorial-path/v1/how-to-win-stats")]
        public static Task<LolNpeTutorialPathAccountSettingsHowToWinStats> GetLolNpeTutorialPathV1HowToWinStats()
            => Sender.Request<LolNpeTutorialPathAccountSettingsHowToWinStats>("get", $"/lol-npe-tutorial-path/v1/how-to-win-stats");
        /// <summary>
        /// <para>POST /lol-npe-tutorial-path/v1/how-to-win-stats/mark-as-seen</para>
        /// </summary>
        [Endpoint("/lol-npe-tutorial-path/v1/how-to-win-stats/mark-as-seen")]
        public static Task<object> PostLolNpeTutorialPathV1HowToWinStatsMarkAsSeen()
            => Sender.Request<object>("post", $"/lol-npe-tutorial-path/v1/how-to-win-stats/mark-as-seen");
        /// <summary>
        /// <para>GET /lol-npe-tutorial-path/v1/rewards/champ</para>
        /// </summary>
        [Endpoint("/lol-npe-tutorial-path/v1/rewards/champ")]
        public static Task<LolNpeTutorialPathCollectionsChampion> GetLolNpeTutorialPathV1RewardsChamp()
            => Sender.Request<LolNpeTutorialPathCollectionsChampion>("get", $"/lol-npe-tutorial-path/v1/rewards/champ");
        /// <summary>
        /// <para>GET /lol-npe-tutorial-path/v1/settings</para>
        /// </summary>
        [Endpoint("/lol-npe-tutorial-path/v1/settings")]
        public static Task<LolNpeTutorialPathAccountSettingsTutorial> GetLolNpeTutorialPathV1Settings()
            => Sender.Request<LolNpeTutorialPathAccountSettingsTutorial>("get", $"/lol-npe-tutorial-path/v1/settings");
        /// <summary>
        /// <para>PATCH /lol-npe-tutorial-path/v1/settings</para>
        /// </summary>
        [Endpoint("/lol-npe-tutorial-path/v1/settings")]
        public static Task PatchLolNpeTutorialPathV1Settings([Parameter("settings", "body")] LolNpeTutorialPathAccountSettingsTutorial settings)
            => Sender.Request("patch", $"/lol-npe-tutorial-path/v1/settings", settings);
        /// <summary>
        /// <para>GET /lol-npe-tutorial-path/v1/tutorials</para>
        /// </summary>
        [Endpoint("/lol-npe-tutorial-path/v1/tutorials")]
        public static Task<LolNpeTutorialPathTutorial[]> GetLolNpeTutorialPathV1Tutorials()
            => Sender.Request<LolNpeTutorialPathTutorial[]>("get", $"/lol-npe-tutorial-path/v1/tutorials");
        /// <summary>
        /// <para>PATCH /lol-npe-tutorial-path/v1/tutorials/init</para>
        /// </summary>
        [Endpoint("/lol-npe-tutorial-path/v1/tutorials/init")]
        public static Task PatchLolNpeTutorialPathV1TutorialsInit()
            => Sender.Request("patch", $"/lol-npe-tutorial-path/v1/tutorials/init");
        /// <summary>
        /// <para>PUT /lol-npe-tutorial-path/v1/tutorials/{tutorialId}/view</para>
        /// </summary>
        [Endpoint("/lol-npe-tutorial-path/v1/tutorials/{tutorialId}/view")]
        public static Task PutLolNpeTutorialPathV1TutorialsByTutorialIdView([Parameter("tutorialId", "path")] string tutorialId)
            => Sender.Request("put", $"/lol-npe-tutorial-path/v1/tutorials/{tutorialId}/view");

        public static string GetURL(string methodName)
        {
            return typeof(LolNpeTutorialPath).GetMethod(methodName).GetCustomAttribute<EndpointAttribute>().URL;
        }
    }
}
