//Auto-generated by https://github.com/pipe01/lcu-api-generator
using GlassLCU.API.Models;
using System.Threading.Tasks;
using static GlassLCU.API.GenerationUtils;
using System.Reflection;

namespace GlassLCU.API.Interfaces
{
    public static class LolPreEndOfGame
    {
        /// <summary>
        /// <para>POST /lol-pre-end-of-game/v1/complete/{sequenceEventName}</para>
        /// </summary>
        [Endpoint("/lol-pre-end-of-game/v1/complete/{sequenceEventName}")]
        public static Task PostLolPreEndOfGameV1CompleteBySequenceEventName([Parameter("sequenceEventName", "path")] string sequenceEventName)
            => Sender.Request("post", $"/lol-pre-end-of-game/v1/complete/{sequenceEventName}");
        /// <summary>
        /// <para>GET /lol-pre-end-of-game/v1/currentSequenceEvent</para>
        /// </summary>
        [Endpoint("/lol-pre-end-of-game/v1/currentSequenceEvent")]
        public static Task<LolPreEndOfGameSequenceEvent> GetLolPreEndOfGameV1CurrentSequenceEvent()
            => Sender.Request<LolPreEndOfGameSequenceEvent>("get", $"/lol-pre-end-of-game/v1/currentSequenceEvent");
        /// <summary>
        /// <para>DELETE /lol-pre-end-of-game/v1/registration/{sequenceEventName}</para>
        /// </summary>
        [Endpoint("/lol-pre-end-of-game/v1/registration/{sequenceEventName}")]
        public static Task DeleteLolPreEndOfGameV1RegistrationBySequenceEventName([Parameter("sequenceEventName", "path")] string sequenceEventName)
            => Sender.Request("delete", $"/lol-pre-end-of-game/v1/registration/{sequenceEventName}");
        /// <summary>
        /// <para>POST /lol-pre-end-of-game/v1/registration/{sequenceEventName}/{priority}</para>
        /// </summary>
        [Endpoint("/lol-pre-end-of-game/v1/registration/{sequenceEventName}/{priority}")]
        public static Task PostLolPreEndOfGameV1RegistrationBySequenceEventNameByPriority([Parameter("sequenceEventName", "path")] string sequenceEventName, [Parameter("priority", "path")] int priority)
            => Sender.Request("post", $"/lol-pre-end-of-game/v1/registration/{sequenceEventName}/{priority}");

        public static string GetURL(string methodName)
        {
            return typeof(LolPreEndOfGame).GetMethod(methodName).GetCustomAttribute<EndpointAttribute>().URL;
        }
    }
}
