//Auto-generated by https://github.com/pipe01/lcu-api-generator
using GlassLCU.API.Models;
using System.Threading.Tasks;
using static GlassLCU.API.GenerationUtils;
using System.Reflection;

namespace GlassLCU.API.Interfaces
{
    public static class LolPft
    {
        /// <summary>
        /// <para>POST /lol-pft/v2/events</para>
        /// </summary>
        [Endpoint("/lol-pft/v2/events")]
        public static Task<object> PostLolPftV2Events([Parameter("pftEvent", "body")] LolPftPFTEvent pftEvent)
            => Sender.Request<object>("post", $"/lol-pft/v2/events", pftEvent);
        /// <summary>
        /// <para>GET /lol-pft/v2/survey</para>
        /// </summary>
        [Endpoint("/lol-pft/v2/survey")]
        public static Task<LolPftPFTSurvey> GetLolPftV2Survey()
            => Sender.Request<LolPftPFTSurvey>("get", $"/lol-pft/v2/survey");
        /// <summary>
        /// <para>POST /lol-pft/v2/survey</para>
        /// </summary>
        [Endpoint("/lol-pft/v2/survey")]
        public static Task PostLolPftV2Survey([Parameter("survey", "body")] LolPftPFTSurvey survey)
            => Sender.Request("post", $"/lol-pft/v2/survey", survey);

        public static string GetURL(string methodName)
        {
            return typeof(LolPft).GetMethod(methodName).GetCustomAttribute<EndpointAttribute>().URL;
        }
    }
}
