//Auto-generated by https://github.com/pipe01/lcu-api-generator
using GlassLCU.API.Models;
using System.Threading.Tasks;
using static GlassLCU.API.GenerationUtils;
using System.Reflection;

namespace GlassLCU.API.Interfaces
{
    public static class LolPlayerBehavior
    {
        /// <summary>
        /// <para>GET /lol-player-behavior/v1/ban</para>
        /// </summary>
        [Endpoint("/lol-player-behavior/v1/ban")]
        public static Task<LolPlayerBehaviorBanNotification> GetLolPlayerBehaviorV1Ban()
            => Sender.Request<LolPlayerBehaviorBanNotification>("get", $"/lol-player-behavior/v1/ban");
        /// <summary>
        /// <para>GET /lol-player-behavior/v1/chat-restriction</para>
        /// </summary>
        [Endpoint("/lol-player-behavior/v1/chat-restriction")]
        public static Task<LolPlayerBehaviorRestrictionNotification> GetLolPlayerBehaviorV1ChatRestriction()
            => Sender.Request<LolPlayerBehaviorRestrictionNotification>("get", $"/lol-player-behavior/v1/chat-restriction");
        /// <summary>
        /// <para>GET /lol-player-behavior/v1/config</para>
        /// </summary>
        [Endpoint("/lol-player-behavior/v1/config")]
        public static Task<LolPlayerBehaviorPlayerBehaviorConfig> GetLolPlayerBehaviorV1Config()
            => Sender.Request<LolPlayerBehaviorPlayerBehaviorConfig>("get", $"/lol-player-behavior/v1/config");
        /// <summary>
        /// <para>GET /lol-player-behavior/v1/ranked-restriction</para>
        /// </summary>
        [Endpoint("/lol-player-behavior/v1/ranked-restriction")]
        public static Task<LolPlayerBehaviorRestrictionNotification> GetLolPlayerBehaviorV1RankedRestriction()
            => Sender.Request<LolPlayerBehaviorRestrictionNotification>("get", $"/lol-player-behavior/v1/ranked-restriction");
        /// <summary>
        /// <para>GET /lol-player-behavior/v1/reform-card</para>
        /// </summary>
        [Endpoint("/lol-player-behavior/v1/reform-card")]
        public static Task<LolPlayerBehaviorReformCard> GetLolPlayerBehaviorV1ReformCard()
            => Sender.Request<LolPlayerBehaviorReformCard>("get", $"/lol-player-behavior/v1/reform-card");
        /// <summary>
        /// <para>GET /lol-player-behavior/v1/reporter-feedback</para>
        /// </summary>
        [Endpoint("/lol-player-behavior/v1/reporter-feedback")]
        public static Task<LolPlayerBehaviorReporterFeedback[]> GetLolPlayerBehaviorV1ReporterFeedback()
            => Sender.Request<LolPlayerBehaviorReporterFeedback[]>("get", $"/lol-player-behavior/v1/reporter-feedback");
        /// <summary>
        /// <para>DELETE /lol-player-behavior/v1/reporter-feedback/{id}</para>
        /// </summary>
        [Endpoint("/lol-player-behavior/v1/reporter-feedback/{id}")]
        public static Task<LolPlayerBehaviorReporterFeedback> DeleteLolPlayerBehaviorV1ReporterFeedbackById([Parameter("id", "path")] string id)
            => Sender.Request<LolPlayerBehaviorReporterFeedback>("delete", $"/lol-player-behavior/v1/reporter-feedback/{id}");
        /// <summary>
        /// <para>GET /lol-player-behavior/v1/reporter-feedback/{id}</para>
        /// </summary>
        [Endpoint("/lol-player-behavior/v1/reporter-feedback/{id}")]
        public static Task<LolPlayerBehaviorReporterFeedback> GetLolPlayerBehaviorV1ReporterFeedbackById([Parameter("id", "path")] string id)
            => Sender.Request<LolPlayerBehaviorReporterFeedback>("get", $"/lol-player-behavior/v1/reporter-feedback/{id}");
        /// <summary>
        /// <para>GET /lol-player-behavior/v2/reform-card</para>
        /// </summary>
        [Endpoint("/lol-player-behavior/v2/reform-card")]
        public static Task<LolPlayerBehaviorReformCardV2> GetLolPlayerBehaviorV2ReformCard()
            => Sender.Request<LolPlayerBehaviorReformCardV2>("get", $"/lol-player-behavior/v2/reform-card");

        public static string GetURL(string methodName)
        {
            return typeof(LolPlayerBehavior).GetMethod(methodName).GetCustomAttribute<EndpointAttribute>().URL;
        }
    }
}
