//Auto-generated by https://github.com/pipe01/lcu-api-generator
using GlassLCU.API.Models;
using System.Threading.Tasks;
using static GlassLCU.API.GenerationUtils;
using System.Reflection;

namespace GlassLCU.API.Interfaces
{
    public static class LolPatch
    {
        /// <summary>
        /// <para>GET /lol-patch/v1/environment</para>
        /// </summary>
        [Endpoint("/lol-patch/v1/environment")]
        public static Task<LolPatchChunkingPatcherEnvironment> GetLolPatchV1Environment()
            => Sender.Request<LolPatchChunkingPatcherEnvironment>("get", $"/lol-patch/v1/environment");
        /// <summary>
        /// <para>GET /lol-patch/v1/notifications</para>
        /// </summary>
        [Endpoint("/lol-patch/v1/notifications")]
        public static Task<LolPatchNotification[]> GetLolPatchV1Notifications()
            => Sender.Request<LolPatchNotification[]>("get", $"/lol-patch/v1/notifications");
        /// <summary>
        /// <para>DELETE /lol-patch/v1/notifications/{id}</para>
        /// </summary>
        [Endpoint("/lol-patch/v1/notifications/{id}")]
        public static Task DeleteLolPatchV1NotificationsById([Parameter("id", "path")] string id)
            => Sender.Request("delete", $"/lol-patch/v1/notifications/{id}");
        /// <summary>
        /// <para>POST /lol-patch/v1/products/league_of_legends/detect-corruption-request</para>
        /// </summary>
        [Endpoint("/lol-patch/v1/products/league_of_legends/detect-corruption-request")]
        public static Task PostLolPatchV1ProductsLeagueOfLegendsDetectCorruptionRequest()
            => Sender.Request("post", $"/lol-patch/v1/products/league_of_legends/detect-corruption-request");
        /// <summary>
        /// <para>GET /lol-patch/v1/products/league_of_legends/install-location</para>
        /// </summary>
        [Endpoint("/lol-patch/v1/products/league_of_legends/install-location")]
        public static Task<LolPatchInstallPaths> GetLolPatchV1ProductsLeagueOfLegendsInstallLocation()
            => Sender.Request<LolPatchInstallPaths>("get", $"/lol-patch/v1/products/league_of_legends/install-location");
        /// <summary>
        /// <para>POST /lol-patch/v1/products/league_of_legends/partial-repair-request</para>
        /// </summary>
        [Endpoint("/lol-patch/v1/products/league_of_legends/partial-repair-request")]
        public static Task PostLolPatchV1ProductsLeagueOfLegendsPartialRepairRequest()
            => Sender.Request("post", $"/lol-patch/v1/products/league_of_legends/partial-repair-request");
        /// <summary>
        /// <para>POST /lol-patch/v1/products/league_of_legends/start-checking-request</para>
        /// </summary>
        [Endpoint("/lol-patch/v1/products/league_of_legends/start-checking-request")]
        public static Task PostLolPatchV1ProductsLeagueOfLegendsStartCheckingRequest()
            => Sender.Request("post", $"/lol-patch/v1/products/league_of_legends/start-checking-request");
        /// <summary>
        /// <para>POST /lol-patch/v1/products/league_of_legends/start-patching-request</para>
        /// </summary>
        [Endpoint("/lol-patch/v1/products/league_of_legends/start-patching-request")]
        public static Task PostLolPatchV1ProductsLeagueOfLegendsStartPatchingRequest()
            => Sender.Request("post", $"/lol-patch/v1/products/league_of_legends/start-patching-request");
        /// <summary>
        /// <para>GET /lol-patch/v1/products/league_of_legends/state</para>
        /// </summary>
        [Endpoint("/lol-patch/v1/products/league_of_legends/state")]
        public static Task<LolPatchProductState> GetLolPatchV1ProductsLeagueOfLegendsState()
            => Sender.Request<LolPatchProductState>("get", $"/lol-patch/v1/products/league_of_legends/state");
        /// <summary>
        /// <para>POST /lol-patch/v1/products/league_of_legends/stop-checking-request</para>
        /// </summary>
        [Endpoint("/lol-patch/v1/products/league_of_legends/stop-checking-request")]
        public static Task PostLolPatchV1ProductsLeagueOfLegendsStopCheckingRequest()
            => Sender.Request("post", $"/lol-patch/v1/products/league_of_legends/stop-checking-request");
        /// <summary>
        /// <para>POST /lol-patch/v1/products/league_of_legends/stop-patching-request</para>
        /// </summary>
        [Endpoint("/lol-patch/v1/products/league_of_legends/stop-patching-request")]
        public static Task PostLolPatchV1ProductsLeagueOfLegendsStopPatchingRequest([Parameter("restart", "query")] bool restart)
            => Sender.Request("post", $"/lol-patch/v1/products/league_of_legends/stop-patching-request?restart={System.Net.WebUtility.UrlEncode(restart.ToString())}");
        /// <summary>
        /// <para>PUT /lol-patch/v1/self-update-restart</para>
        /// </summary>
        [Endpoint("/lol-patch/v1/self-update-restart")]
        public static Task PutLolPatchV1SelfUpdateRestart([Parameter("forceRestartOnSelfUpdate", "query")] bool forceRestartOnSelfUpdate)
            => Sender.Request("put", $"/lol-patch/v1/self-update-restart?forceRestartOnSelfUpdate={System.Net.WebUtility.UrlEncode(forceRestartOnSelfUpdate.ToString())}");

        public static string GetURL(string methodName)
        {
            return typeof(LolPatch).GetMethod(methodName).GetCustomAttribute<EndpointAttribute>().URL;
        }
    }
}
