//Auto-generated by https://github.com/pipe01/lcu-api-generator
using GlassLCU.API.Models;
using System.Threading.Tasks;
using static GlassLCU.API.GenerationUtils;
using System.Reflection;

namespace GlassLCU.API.Interfaces
{
    public static class LolRecommendations
    {
        /// <summary>
        /// <para>GET /lol-recommendations/v1/recommendations</para>
        /// </summary>
        [Endpoint("/lol-recommendations/v1/recommendations")]
        public static Task<LolRecommendationsRecommendationsCollection> GetLolRecommendationsV1Recommendations([Parameter("numberOfRecommendations", "query")] int numberOfRecommendations = default)
            => Sender.Request<LolRecommendationsRecommendationsCollection>("get", $"/lol-recommendations/v1/recommendations?{(numberOfRecommendations != default ? $"numberOfRecommendations={System.Net.WebUtility.UrlEncode(numberOfRecommendations.ToString())}" : null)}");

        public static string GetURL(string methodName)
        {
            return typeof(LolRecommendations).GetMethod(methodName).GetCustomAttribute<EndpointAttribute>().URL;
        }
    }
}
