//Auto-generated by https://github.com/pipe01/lcu-api-generator
using GlassLCU.API.Models;
using System.Threading.Tasks;
using static GlassLCU.API.GenerationUtils;
using System.Reflection;

namespace GlassLCU.API.Interfaces
{
    public static class LolSimpleDialogMessages
    {
        /// <summary>
        /// <para>GET /lol-simple-dialog-messages/v1/messages</para>
        /// </summary>
        [Endpoint("/lol-simple-dialog-messages/v1/messages")]
        public static Task<LolSimpleDialogMessagesMessage[]> GetLolSimpleDialogMessagesV1Messages()
            => Sender.Request<LolSimpleDialogMessagesMessage[]>("get", $"/lol-simple-dialog-messages/v1/messages");
        /// <summary>
        /// <para>POST /lol-simple-dialog-messages/v1/messages</para>
        /// </summary>
        [Endpoint("/lol-simple-dialog-messages/v1/messages")]
        public static Task<object> PostLolSimpleDialogMessagesV1Messages([Parameter("messageRequest", "body")] LolSimpleDialogMessagesLocalMessageRequest messageRequest)
            => Sender.Request<object>("post", $"/lol-simple-dialog-messages/v1/messages", messageRequest);
        /// <summary>
        /// <para>DELETE /lol-simple-dialog-messages/v1/messages/{messageId}</para>
        /// </summary>
        [Endpoint("/lol-simple-dialog-messages/v1/messages/{messageId}")]
        public static Task<object> DeleteLolSimpleDialogMessagesV1MessagesByMessageId([Parameter("messageId", "path")] long messageId)
            => Sender.Request<object>("delete", $"/lol-simple-dialog-messages/v1/messages/{messageId}");

        public static string GetURL(string methodName)
        {
            return typeof(LolSimpleDialogMessages).GetMethod(methodName).GetCustomAttribute<EndpointAttribute>().URL;
        }
    }
}
