//Auto-generated by https://github.com/pipe01/lcu-api-generator
using GlassLCU.API.Models;
using System.Threading.Tasks;
using static GlassLCU.API.GenerationUtils;
using System.Reflection;

namespace GlassLCU.API.Interfaces
{
    public static class LolSettings
    {
        /// <summary>
        /// <para>GET /lol-settings/v1/account/didreset</para>
        /// </summary>
        [Endpoint("/lol-settings/v1/account/didreset")]
        public static Task<bool> GetLolSettingsV1AccountDidreset()
            => Sender.Request<bool>("get", $"/lol-settings/v1/account/didreset");
        /// <summary>
        /// <para>POST /lol-settings/v1/account/save</para>
        /// </summary>
        [Endpoint("/lol-settings/v1/account/save")]
        public static Task PostLolSettingsV1AccountSave()
            => Sender.Request("post", $"/lol-settings/v1/account/save");
        /// <summary>
        /// <para>GET /lol-settings/v1/account/{category}</para>
        /// </summary>
        [Endpoint("/lol-settings/v1/account/{category}")]
        public static Task<object> GetLolSettingsV1AccountByCategory([Parameter("category", "path")] string category)
            => Sender.Request<object>("get", $"/lol-settings/v1/account/{category}");
        /// <summary>
        /// <para>PATCH /lol-settings/v1/account/{category}</para>
        /// </summary>
        [Endpoint("/lol-settings/v1/account/{category}")]
        public static Task<object> PatchLolSettingsV1AccountByCategory([Parameter("category", "path")] string category, [Parameter("settingsResource", "body")] LolSettingsSettingCategory settingsResource)
            => Sender.Request<object>("patch", $"/lol-settings/v1/account/{category}", settingsResource);
        /// <summary>
        /// <para>PUT /lol-settings/v1/account/{category}</para>
        /// </summary>
        [Endpoint("/lol-settings/v1/account/{category}")]
        public static Task<object> PutLolSettingsV1AccountByCategory([Parameter("category", "path")] string category, [Parameter("settingsResource", "body")] LolSettingsSettingCategory settingsResource)
            => Sender.Request<object>("put", $"/lol-settings/v1/account/{category}", settingsResource);
        /// <summary>
        /// <para>GET /lol-settings/v1/local/{category}</para>
        /// </summary>
        [Endpoint("/lol-settings/v1/local/{category}")]
        public static Task<object> GetLolSettingsV1LocalByCategory([Parameter("category", "path")] string category)
            => Sender.Request<object>("get", $"/lol-settings/v1/local/{category}");
        /// <summary>
        /// <para>PATCH /lol-settings/v1/local/{category}</para>
        /// </summary>
        [Endpoint("/lol-settings/v1/local/{category}")]
        public static Task<object> PatchLolSettingsV1LocalByCategory([Parameter("category", "path")] string category, [Parameter("settingsResource", "body")] LolSettingsSettingCategory settingsResource)
            => Sender.Request<object>("patch", $"/lol-settings/v1/local/{category}", settingsResource);
        /// <summary>
        /// <para>GET /lol-settings/v2/account/{ppType}/{category}</para>
        /// </summary>
        [Endpoint("/lol-settings/v2/account/{ppType}/{category}")]
        public static Task<object> GetLolSettingsV2AccountByPpTypeByCategory([Parameter("ppType", "path")] string ppType, [Parameter("category", "path")] string category)
            => Sender.Request<object>("get", $"/lol-settings/v2/account/{ppType}/{category}");
        /// <summary>
        /// <para>PATCH /lol-settings/v2/account/{ppType}/{category}</para>
        /// </summary>
        [Endpoint("/lol-settings/v2/account/{ppType}/{category}")]
        public static Task<object> PatchLolSettingsV2AccountByPpTypeByCategory([Parameter("ppType", "path")] string ppType, [Parameter("category", "path")] string category, [Parameter("settingsResource", "body")] LolSettingsSettingCategory settingsResource)
            => Sender.Request<object>("patch", $"/lol-settings/v2/account/{ppType}/{category}", settingsResource);
        /// <summary>
        /// <para>PUT /lol-settings/v2/account/{ppType}/{category}</para>
        /// </summary>
        [Endpoint("/lol-settings/v2/account/{ppType}/{category}")]
        public static Task<object> PutLolSettingsV2AccountByPpTypeByCategory([Parameter("ppType", "path")] string ppType, [Parameter("category", "path")] string category, [Parameter("settingsResource", "body")] LolSettingsSettingCategory settingsResource)
            => Sender.Request<object>("put", $"/lol-settings/v2/account/{ppType}/{category}", settingsResource);
        /// <summary>
        /// <para>GET /lol-settings/v2/didreset/{ppType}</para>
        /// </summary>
        [Endpoint("/lol-settings/v2/didreset/{ppType}")]
        public static Task<bool> GetLolSettingsV2DidresetByPpType([Parameter("ppType", "path")] string ppType)
            => Sender.Request<bool>("get", $"/lol-settings/v2/didreset/{ppType}");
        /// <summary>
        /// <para>GET /lol-settings/v2/local/{category}</para>
        /// </summary>
        [Endpoint("/lol-settings/v2/local/{category}")]
        public static Task<object> GetLolSettingsV2LocalByCategory([Parameter("category", "path")] string category)
            => Sender.Request<object>("get", $"/lol-settings/v2/local/{category}");
        /// <summary>
        /// <para>PATCH /lol-settings/v2/local/{category}</para>
        /// </summary>
        [Endpoint("/lol-settings/v2/local/{category}")]
        public static Task<object> PatchLolSettingsV2LocalByCategory([Parameter("category", "path")] string category, [Parameter("settingsResource", "body")] LolSettingsSettingCategory settingsResource)
            => Sender.Request<object>("patch", $"/lol-settings/v2/local/{category}", settingsResource);
        /// <summary>
        /// <para>GET /lol-settings/v2/ready</para>
        /// </summary>
        [Endpoint("/lol-settings/v2/ready")]
        public static Task<bool> GetLolSettingsV2Ready()
            => Sender.Request<bool>("get", $"/lol-settings/v2/ready");

        public static string GetURL(string methodName)
        {
            return typeof(LolSettings).GetMethod(methodName).GetCustomAttribute<EndpointAttribute>().URL;
        }
    }
}
