//Auto-generated by https://github.com/pipe01/lcu-api-generator
using GlassLCU.API.Models;
using System.Threading.Tasks;
using static GlassLCU.API.GenerationUtils;
using System.Reflection;

namespace GlassLCU.API.Interfaces
{
    public static class LolSpectator
    {
        /// <summary>
        /// <para>POST /lol-spectator/v1/buddy/spectate</para>
        /// </summary>
        [Endpoint("/lol-spectator/v1/buddy/spectate")]
        public static Task<LolSpectatorSummonerOrTeamAvailabilty> PostLolSpectatorV1BuddySpectate([Parameter("summonerOrTeamNames", "body")] string[] summonerOrTeamNames)
            => Sender.Request<LolSpectatorSummonerOrTeamAvailabilty>("post", $"/lol-spectator/v1/buddy/spectate", summonerOrTeamNames);
        /// <summary>
        /// <para>GET /lol-spectator/v1/spectate</para>
        /// </summary>
        [Endpoint("/lol-spectator/v1/spectate")]
        public static Task<LolSpectatorSpectateGameInfo> GetLolSpectatorV1Spectate()
            => Sender.Request<LolSpectatorSpectateGameInfo>("get", $"/lol-spectator/v1/spectate");
        /// <summary>
        /// <para>POST /lol-spectator/v1/spectate/launch</para>
        /// </summary>
        [Endpoint("/lol-spectator/v1/spectate/launch")]
        public static Task<object> PostLolSpectatorV1SpectateLaunch([Parameter("spectateGameInfo", "body")] LolSpectatorSpectateGameInfo spectateGameInfo)
            => Sender.Request<object>("post", $"/lol-spectator/v1/spectate/launch", spectateGameInfo);

        public static string GetURL(string methodName)
        {
            return typeof(LolSpectator).GetMethod(methodName).GetCustomAttribute<EndpointAttribute>().URL;
        }
    }
}
