//Auto-generated by https://github.com/pipe01/lcu-api-generator
using GlassLCU.API.Models;
using System.Threading.Tasks;
using static GlassLCU.API.GenerationUtils;
using System.Reflection;

namespace GlassLCU.API.Interfaces
{
    public static class LolTrophies
    {
        /// <summary>
        /// <para>GET /lol-trophies/v1/current-summoner/trophies/profile</para>
        /// </summary>
        [Endpoint("/lol-trophies/v1/current-summoner/trophies/profile")]
        public static Task<LolTrophiesTrophyProfileData> GetLolTrophiesV1CurrentSummonerTrophiesProfile()
            => Sender.Request<LolTrophiesTrophyProfileData>("get", $"/lol-trophies/v1/current-summoner/trophies/profile");
        /// <summary>
        /// <para>GET /lol-trophies/v1/players/{puuid}/trophies/profile</para>
        /// </summary>
        [Endpoint("/lol-trophies/v1/players/{puuid}/trophies/profile")]
        public static Task<LolTrophiesTrophyProfileData> GetLolTrophiesV1PlayersByPuuidTrophiesProfile([Parameter("puuid", "path")] string puuid)
            => Sender.Request<LolTrophiesTrophyProfileData>("get", $"/lol-trophies/v1/players/{puuid}/trophies/profile");

        public static string GetURL(string methodName)
        {
            return typeof(LolTrophies).GetMethod(methodName).GetCustomAttribute<EndpointAttribute>().URL;
        }
    }
}
