//Auto-generated by https://github.com/pipe01/lcu-api-generator
using GlassLCU.API.Models;
using System.Threading.Tasks;
using static GlassLCU.API.GenerationUtils;
using System.Reflection;

namespace GlassLCU.API.Interfaces
{
    public static class Patcher
    {
        /// <summary>
        /// <para>GET /patcher/v1/executable-version</para>
        /// </summary>
        [Endpoint("/patcher/v1/executable-version")]
        public static Task<string> GetPatcherV1ExecutableVersion()
            => Sender.Request<string>("get", $"/patcher/v1/executable-version");
        /// <summary>
        /// <para>GET /patcher/v1/notifications</para>
        /// </summary>
        [Endpoint("/patcher/v1/notifications")]
        public static Task<PatcherNotification[]> GetPatcherV1Notifications()
            => Sender.Request<PatcherNotification[]>("get", $"/patcher/v1/notifications");
        /// <summary>
        /// <para>POST /patcher/v1/notifications</para>
        /// </summary>
        [Endpoint("/patcher/v1/notifications")]
        public static Task PostPatcherV1Notifications([Parameter("notificationId", "query")] string notificationId)
            => Sender.Request("post", $"/patcher/v1/notifications?notificationId={System.Net.WebUtility.UrlEncode(notificationId.ToString())}");
        /// <summary>
        /// <para>DELETE /patcher/v1/notifications/{id}</para>
        /// </summary>
        [Endpoint("/patcher/v1/notifications/{id}")]
        public static Task<object> DeletePatcherV1NotificationsById([Parameter("id", "path")] string id)
            => Sender.Request<object>("delete", $"/patcher/v1/notifications/{id}");
        /// <summary>
        /// <para>GET /patcher/v1/p2p/status</para>
        /// </summary>
        [Endpoint("/patcher/v1/p2p/status")]
        public static Task<PatcherP2PStatus> GetPatcherV1P2pStatus()
            => Sender.Request<PatcherP2PStatus>("get", $"/patcher/v1/p2p/status");
        /// <summary>
        /// <para>PATCH /patcher/v1/p2p/status</para>
        /// </summary>
        [Endpoint("/patcher/v1/p2p/status")]
        public static Task<object> PatchPatcherV1P2pStatus([Parameter("data", "body")] PatcherP2PStatusUpdate data)
            => Sender.Request<object>("patch", $"/patcher/v1/p2p/status", data);
        /// <summary>
        /// <para>GET /patcher/v1/products</para>
        /// </summary>
        [Endpoint("/patcher/v1/products")]
        public static Task<string[]> GetPatcherV1Products()
            => Sender.Request<string[]>("get", $"/patcher/v1/products");
        /// <summary>
        /// <para>POST /patcher/v1/products/league_of_legends/full-repair-request</para>
        /// </summary>
        [Endpoint("/patcher/v1/products/league_of_legends/full-repair-request")]
        public static Task<object> PostPatcherV1ProductsLeagueOfLegendsFullRepairRequest()
            => Sender.Request<object>("post", $"/patcher/v1/products/league_of_legends/full-repair-request");
        /// <summary>
        /// <para>DELETE /patcher/v1/products/{product-id}</para>
        /// </summary>
        [Endpoint("/patcher/v1/products/{product-id}")]
        public static Task<object> DeletePatcherV1ProductsByProductId([Parameter("product-id", "path")] string productId)
            => Sender.Request<object>("delete", $"/patcher/v1/products/{productId}");
        /// <summary>
        /// <para>PUT /patcher/v1/products/{product-id}</para>
        /// </summary>
        [Endpoint("/patcher/v1/products/{product-id}")]
        public static Task<object> PutPatcherV1ProductsByProductId([Parameter("product-id", "path")] string productId, [Parameter("data", "body")] PatcherProductResource data)
            => Sender.Request<object>("put", $"/patcher/v1/products/{productId}", data);
        /// <summary>
        /// <para>POST /patcher/v1/products/{product-id}/detect-corruption-request</para>
        /// </summary>
        [Endpoint("/patcher/v1/products/{product-id}/detect-corruption-request")]
        public static Task<PatcherProductState> PostPatcherV1ProductsByProductIdDetectCorruptionRequest([Parameter("product-id", "path")] string productId)
            => Sender.Request<PatcherProductState>("post", $"/patcher/v1/products/{productId}/detect-corruption-request");
        /// <summary>
        /// <para>POST /patcher/v1/products/{product-id}/inject-error</para>
        /// </summary>
        [Endpoint("/patcher/v1/products/{product-id}/inject-error")]
        public static Task PostPatcherV1ProductsByProductIdInjectError([Parameter("product-id", "path")] string productId, [Parameter("component-id", "query")] string componentId, [Parameter("error", "query")] string error)
            => Sender.Request("post", $"/patcher/v1/products/{productId}/inject-error?component-id={System.Net.WebUtility.UrlEncode(componentId.ToString())}&error={System.Net.WebUtility.UrlEncode(error.ToString())}");
        /// <summary>
        /// <para>POST /patcher/v1/products/{product-id}/partial-repair-request</para>
        /// </summary>
        [Endpoint("/patcher/v1/products/{product-id}/partial-repair-request")]
        public static Task<object> PostPatcherV1ProductsByProductIdPartialRepairRequest([Parameter("product-id", "path")] string productId)
            => Sender.Request<object>("post", $"/patcher/v1/products/{productId}/partial-repair-request");
        /// <summary>
        /// <para>GET /patcher/v1/products/{product-id}/paths</para>
        /// </summary>
        [Endpoint("/patcher/v1/products/{product-id}/paths")]
        public static Task<object> GetPatcherV1ProductsByProductIdPaths([Parameter("product-id", "path")] string productId)
            => Sender.Request<object>("get", $"/patcher/v1/products/{productId}/paths");
        /// <summary>
        /// <para>POST /patcher/v1/products/{product-id}/signal-start-patching-delayed</para>
        /// </summary>
        [Endpoint("/patcher/v1/products/{product-id}/signal-start-patching-delayed")]
        public static Task<object> PostPatcherV1ProductsByProductIdSignalStartPatchingDelayed([Parameter("product-id", "path")] string productId)
            => Sender.Request<object>("post", $"/patcher/v1/products/{productId}/signal-start-patching-delayed");
        /// <summary>
        /// <para>POST /patcher/v1/products/{product-id}/start-checking-request</para>
        /// </summary>
        [Endpoint("/patcher/v1/products/{product-id}/start-checking-request")]
        public static Task<object> PostPatcherV1ProductsByProductIdStartCheckingRequest([Parameter("product-id", "path")] string productId)
            => Sender.Request<object>("post", $"/patcher/v1/products/{productId}/start-checking-request");
        /// <summary>
        /// <para>POST /patcher/v1/products/{product-id}/start-patching-request</para>
        /// </summary>
        [Endpoint("/patcher/v1/products/{product-id}/start-patching-request")]
        public static Task<object> PostPatcherV1ProductsByProductIdStartPatchingRequest([Parameter("product-id", "path")] string productId)
            => Sender.Request<object>("post", $"/patcher/v1/products/{productId}/start-patching-request");
        /// <summary>
        /// <para>GET /patcher/v1/products/{product-id}/state</para>
        /// </summary>
        [Endpoint("/patcher/v1/products/{product-id}/state")]
        public static Task<PatcherProductState> GetPatcherV1ProductsByProductIdState([Parameter("product-id", "path")] string productId)
            => Sender.Request<PatcherProductState>("get", $"/patcher/v1/products/{productId}/state");
        /// <summary>
        /// <para>POST /patcher/v1/products/{product-id}/stop-checking-request</para>
        /// </summary>
        [Endpoint("/patcher/v1/products/{product-id}/stop-checking-request")]
        public static Task<object> PostPatcherV1ProductsByProductIdStopCheckingRequest([Parameter("product-id", "path")] string productId)
            => Sender.Request<object>("post", $"/patcher/v1/products/{productId}/stop-checking-request");
        /// <summary>
        /// <para>POST /patcher/v1/products/{product-id}/stop-patching-request</para>
        /// </summary>
        [Endpoint("/patcher/v1/products/{product-id}/stop-patching-request")]
        public static Task<object> PostPatcherV1ProductsByProductIdStopPatchingRequest([Parameter("product-id", "path")] string productId)
            => Sender.Request<object>("post", $"/patcher/v1/products/{productId}/stop-patching-request");
        /// <summary>
        /// <para>GET /patcher/v1/products/{product-id}/tags</para>
        /// </summary>
        [Endpoint("/patcher/v1/products/{product-id}/tags")]
        public static Task<object> GetPatcherV1ProductsByProductIdTags([Parameter("product-id", "path")] string productId)
            => Sender.Request<object>("get", $"/patcher/v1/products/{productId}/tags");
        /// <summary>
        /// <para>DELETE /patcher/v1/products/{product-id}/{component-id}/http-headers</para>
        /// </summary>
        [Endpoint("/patcher/v1/products/{product-id}/{component-id}/http-headers")]
        public static Task<object> DeletePatcherV1ProductsByProductIdByComponentIdHttpHeaders([Parameter("product-id", "path")] string productId, [Parameter("component-id", "path")] string componentId)
            => Sender.Request<object>("delete", $"/patcher/v1/products/{productId}/{componentId}/http-headers");
        /// <summary>
        /// <para>PUT /patcher/v1/products/{product-id}/{component-id}/http-headers</para>
        /// </summary>
        [Endpoint("/patcher/v1/products/{product-id}/{component-id}/http-headers")]
        public static Task<object> PutPatcherV1ProductsByProductIdByComponentIdHttpHeaders([Parameter("product-id", "path")] string productId, [Parameter("component-id", "path")] string componentId, [Parameter("headers", "body")] PatcherHeaderEntry[] headers)
            => Sender.Request<object>("put", $"/patcher/v1/products/{productId}/{componentId}/http-headers", headers);
        /// <summary>
        /// <para>PUT /patcher/v1/self-update-restart</para>
        /// </summary>
        [Endpoint("/patcher/v1/self-update-restart")]
        public static Task<object> PutPatcherV1SelfUpdateRestart([Parameter("forceRestartOnSelfUpdate", "query")] bool forceRestartOnSelfUpdate)
            => Sender.Request<object>("put", $"/patcher/v1/self-update-restart?forceRestartOnSelfUpdate={System.Net.WebUtility.UrlEncode(forceRestartOnSelfUpdate.ToString())}");
        /// <summary>
        /// <para>GET /patcher/v1/status</para>
        /// </summary>
        [Endpoint("/patcher/v1/status")]
        public static Task<PatcherStatus> GetPatcherV1Status()
            => Sender.Request<PatcherStatus>("get", $"/patcher/v1/status");

        public static string GetURL(string methodName)
        {
            return typeof(Patcher).GetMethod(methodName).GetCustomAttribute<EndpointAttribute>().URL;
        }
    }
}
