//Auto-generated by https://github.com/pipe01/lcu-api-generator
using GlassLCU.API.Models;
using System.Threading.Tasks;
using static GlassLCU.API.GenerationUtils;
using System.Reflection;

namespace GlassLCU.API.Interfaces
{
    public static class RsoAuth
    {
        /// <summary>
        /// <para>DELETE /rso-auth/v1/authorization</para>
        /// </summary>
        [Endpoint("/rso-auth/v1/authorization")]
        public static Task DeleteRsoAuthV1Authorization()
            => Sender.Request("delete", $"/rso-auth/v1/authorization");
        /// <summary>
        /// <para>GET /rso-auth/v1/authorization</para>
        /// </summary>
        [Endpoint("/rso-auth/v1/authorization")]
        public static Task<RsoAuthAuthorization> GetRsoAuthV1Authorization()
            => Sender.Request<RsoAuthAuthorization>("get", $"/rso-auth/v1/authorization");
        /// <summary>
        /// <para>GET /rso-auth/v1/authorization/access-token</para>
        /// </summary>
        [Endpoint("/rso-auth/v1/authorization/access-token")]
        public static Task<RsoAuthAccessToken> GetRsoAuthV1AuthorizationAccessToken()
            => Sender.Request<RsoAuthAccessToken>("get", $"/rso-auth/v1/authorization/access-token");
        /// <summary>
        /// <para>GET /rso-auth/v1/authorization/entitlements-token</para>
        /// </summary>
        [Endpoint("/rso-auth/v1/authorization/entitlements-token")]
        public static Task<RsoAuthEntitlementsToken> GetRsoAuthV1AuthorizationEntitlementsToken()
            => Sender.Request<RsoAuthEntitlementsToken>("get", $"/rso-auth/v1/authorization/entitlements-token");
        /// <summary>
        /// <para>GET /rso-auth/v1/authorization/error</para>
        /// </summary>
        [Endpoint("/rso-auth/v1/authorization/error")]
        public static Task<RsoAuthAuthError> GetRsoAuthV1AuthorizationError()
            => Sender.Request<RsoAuthAuthError>("get", $"/rso-auth/v1/authorization/error");
        /// <summary>
        /// <para>POST /rso-auth/v1/authorization/gas</para>
        /// </summary>
        [Endpoint("/rso-auth/v1/authorization/gas")]
        public static Task<RsoAuthAuthorization> PostRsoAuthV1AuthorizationGas([Parameter("creds", "body")] RsoAuthRSOPlayerCredentials creds)
            => Sender.Request<RsoAuthAuthorization>("post", $"/rso-auth/v1/authorization/gas", creds);
        /// <summary>
        /// <para>GET /rso-auth/v1/authorization/gas-token</para>
        /// </summary>
        [Endpoint("/rso-auth/v1/authorization/gas-token")]
        public static Task<object> GetRsoAuthV1AuthorizationGasToken()
            => Sender.Request<object>("get", $"/rso-auth/v1/authorization/gas-token");
        /// <summary>
        /// <para>GET /rso-auth/v1/authorization/id-token</para>
        /// </summary>
        [Endpoint("/rso-auth/v1/authorization/id-token")]
        public static Task<RsoAuthIdToken> GetRsoAuthV1AuthorizationIdToken()
            => Sender.Request<RsoAuthIdToken>("get", $"/rso-auth/v1/authorization/id-token");
        /// <summary>
        /// <para>POST /rso-auth/v1/authorization/refresh</para>
        /// </summary>
        [Endpoint("/rso-auth/v1/authorization/refresh")]
        public static Task<RsoAuthAuthorization> PostRsoAuthV1AuthorizationRefresh()
            => Sender.Request<RsoAuthAuthorization>("post", $"/rso-auth/v1/authorization/refresh");
        /// <summary>
        /// <para>GET /rso-auth/v1/authorization/userinfo</para>
        /// </summary>
        [Endpoint("/rso-auth/v1/authorization/userinfo")]
        public static Task<RsoAuthUserInfo> GetRsoAuthV1AuthorizationUserinfo()
            => Sender.Request<RsoAuthUserInfo>("get", $"/rso-auth/v1/authorization/userinfo");
        /// <summary>
        /// <para>POST /rso-auth/v1/authorization/userinfo</para>
        /// </summary>
        [Endpoint("/rso-auth/v1/authorization/userinfo")]
        public static Task<RsoAuthUserInfo> PostRsoAuthV1AuthorizationUserinfo()
            => Sender.Request<RsoAuthUserInfo>("post", $"/rso-auth/v1/authorization/userinfo");
        /// <summary>
        /// <para>DELETE /rso-auth/v1/config</para>
        /// </summary>
        [Endpoint("/rso-auth/v1/config")]
        public static Task DeleteRsoAuthV1Config()
            => Sender.Request("delete", $"/rso-auth/v1/config");
        /// <summary>
        /// <para>POST /rso-auth/v1/config</para>
        /// </summary>
        [Endpoint("/rso-auth/v1/config")]
        public static Task PostRsoAuthV1Config([Parameter("config", "body")] RsoAuthRSOJWTConfig config)
            => Sender.Request("post", $"/rso-auth/v1/config", config);
        /// <summary>
        /// <para>PUT /rso-auth/v1/config</para>
        /// </summary>
        [Endpoint("/rso-auth/v1/config")]
        public static Task PutRsoAuthV1Config([Parameter("config", "body")] RsoAuthRSOJWTConfig config)
            => Sender.Request("put", $"/rso-auth/v1/config", config);
        /// <summary>
        /// <para>GET /rso-auth/v1/config/{platformId}</para>
        /// </summary>
        [Endpoint("/rso-auth/v1/config/{platformId}")]
        public static Task<RsoAuthRSOJWTConfig> GetRsoAuthV1ConfigByPlatformId([Parameter("platformId", "path")] string platformId)
            => Sender.Request<RsoAuthRSOJWTConfig>("get", $"/rso-auth/v1/config/{platformId}");
        /// <summary>
        /// <para>POST /rso-auth/v1/device-id</para>
        /// </summary>
        [Endpoint("/rso-auth/v1/device-id")]
        public static Task<RsoAuthDeviceId> PostRsoAuthV1DeviceId()
            => Sender.Request<RsoAuthDeviceId>("post", $"/rso-auth/v1/device-id");
        /// <summary>
        /// <para>GET /rso-auth/v1/status/{platformId}</para>
        /// </summary>
        [Endpoint("/rso-auth/v1/status/{platformId}")]
        public static Task<RsoAuthRegionStatus> GetRsoAuthV1StatusByPlatformId([Parameter("platformId", "path")] string platformId)
            => Sender.Request<RsoAuthRegionStatus>("get", $"/rso-auth/v1/status/{platformId}");
        /// <summary>
        /// <para>DELETE /rso-auth/v2/config</para>
        /// </summary>
        [Endpoint("/rso-auth/v2/config")]
        public static Task DeleteRsoAuthV2Config()
            => Sender.Request("delete", $"/rso-auth/v2/config");
        /// <summary>
        /// <para>POST /rso-auth/v2/config</para>
        /// </summary>
        [Endpoint("/rso-auth/v2/config")]
        public static Task PostRsoAuthV2Config([Parameter("config", "body")] RsoAuthPublicClientConfig config)
            => Sender.Request("post", $"/rso-auth/v2/config", config);

        public static string GetURL(string methodName)
        {
            return typeof(RsoAuth).GetMethod(methodName).GetCustomAttribute<EndpointAttribute>().URL;
        }
    }
}
