//Auto-generated by https://github.com/pipe01/lcu-api-generator
using GlassLCU.API.Models;
using System.Threading.Tasks;
using static GlassLCU.API.GenerationUtils;
using System.Reflection;

namespace GlassLCU.API.Interfaces
{
    public static class Sanitizer
    {
        /// <summary>
        /// <para>POST /sanitizer/v1/containsSanitized</para>
        /// </summary>
        [Endpoint("/sanitizer/v1/containsSanitized")]
        public static Task<SanitizerContainsSanitizedResponse> PostSanitizerV1ContainsSanitized([Parameter("request", "body")] SanitizerContainsSanitizedRequest request)
            => Sender.Request<SanitizerContainsSanitizedResponse>("post", $"/sanitizer/v1/containsSanitized", request);
        /// <summary>
        /// <para>POST /sanitizer/v1/sanitize</para>
        /// </summary>
        [Endpoint("/sanitizer/v1/sanitize")]
        public static Task<SanitizerSanitizeResponse> PostSanitizerV1Sanitize([Parameter("request", "body")] SanitizerSanitizeRequest request)
            => Sender.Request<SanitizerSanitizeResponse>("post", $"/sanitizer/v1/sanitize", request);
        /// <summary>
        /// <para>GET /sanitizer/v1/status</para>
        /// </summary>
        [Endpoint("/sanitizer/v1/status")]
        public static Task<SanitizerSanitizerStatus> GetSanitizerV1Status()
            => Sender.Request<SanitizerSanitizerStatus>("get", $"/sanitizer/v1/status");

        public static string GetURL(string methodName)
        {
            return typeof(Sanitizer).GetMethod(methodName).GetCustomAttribute<EndpointAttribute>().URL;
        }
    }
}
