//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    [JsonObject]
    public class ActiveBoostsLcdsSummonerActiveBoostsDTO
    {
        [JsonProperty("ipBoostEndDate")]
        public long IpBoostEndDate { get; set; }
        [JsonProperty("ipBoostPerWinCount")]
        public int IpBoostPerWinCount { get; set; }
        [JsonProperty("ipLoyaltyBoost")]
        public int IpLoyaltyBoost { get; set; }
        [JsonProperty("summonerId")]
        public long SummonerId { get; set; }
        [JsonProperty("xpBoostEndDate")]
        public long XpBoostEndDate { get; set; }
        [JsonProperty("xpBoostPerWinCount")]
        public int XpBoostPerWinCount { get; set; }
        [JsonProperty("xpLoyaltyBoost")]
        public int XpLoyaltyBoost { get; set; }
    }
}
