//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    [JsonObject]
    public class AllPublicSummonerDataDTO
    {
        [JsonProperty("summoner")]
        public BasePublicSummonerDTO Summoner { get; set; }
        [JsonProperty("summonerLevelAndPoints")]
        public SummonerLevelAndPoints SummonerLevelAndPoints { get; set; }
    }
}
