//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    public enum ClashRewardKeyType
    {
        TIER,
        CUP,
        TOKENS,
        LOWEST_POSITION,
        WINS,
        THEME_VP,
        SEASON_VP,
        SEASON_FLAG_COUNT,
    }
}
