//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    [JsonObject]
    public class LcdsGameInviteBaseRuntimeException
    {
        [JsonProperty("rootCauseClassname")]
        public string RootCauseClassname { get; set; }
    }
}
