//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    [JsonObject]
    public class LolBannersClashV2FrameRewardSpec
    {
        [JsonProperty("level")]
        public string Level { get; set; }
        [JsonProperty("seasonId")]
        public string SeasonId { get; set; }
    }
}
