//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    [JsonObject]
    public class LolBannersInventoryResponse
    {
        [JsonProperty("items")]
        public LolBannersInventoryItemsByType Items { get; set; }
    }
}
