//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    [JsonObject]
    public class LolClubsPlayerMembershipDto
    {
        [JsonProperty("activeClubs")]
        public LolClubsClubDto[] ActiveClubs { get; set; }
        [JsonProperty("clubsServerConfig")]
        public LolClubsClubsServerConfigDto ClubsServerConfig { get; set; }
        [JsonProperty("pendingInvites")]
        public LolClubsMembershipInviteDto[] PendingInvites { get; set; }
        [JsonProperty("player")]
        public LolClubsPlayerInfoDto Player { get; set; }
        [JsonProperty("playerClubPreferences")]
        public LolClubsPlayerMembershipPreferencesDto PlayerClubPreferences { get; set; }
        [JsonProperty("removedClubs")]
        public LolClubsClubReferenceDto[] RemovedClubs { get; set; }
        [JsonProperty("resourceUri")]
        public string ResourceUri { get; set; }
        [JsonProperty("revokedInviteClubs")]
        public LolClubsClubReferenceDto[] RevokedInviteClubs { get; set; }
        [JsonProperty("secureClubPresenceInfoString")]
        public string SecureClubPresenceInfoString { get; set; }
    }
}
