//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    [JsonObject]
    public class LolClubsRosterItemDto
    {
        [JsonProperty("accountId")]
        public long AccountId { get; set; }
        [JsonProperty("clubRole")]
        public string ClubRole { get; set; }
        [JsonProperty("summonerIconId")]
        public int SummonerIconId { get; set; }
        [JsonProperty("summonerName")]
        public string SummonerName { get; set; }
    }
}
