//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    public enum LolCollectionsCollectionsSummonerBackdropType
    {
        Default,
        Summoner_icon,
        Recently_played,
        Highest_mastery,
        Specified_skin,
    }
}
