//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    [JsonObject]
    public class LolClashGameflowSession
    {
        [JsonProperty("phase")]
        public LolClashGameflowPhase Phase { get; set; }
    }
}
