//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    [JsonObject]
    public class LolChampionsLcdsDynamicClientConfig
    {
        [JsonProperty("DisabledChampions")]
        public object DisabledChampions { get; set; }
    }
}
