//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    [JsonObject]
    public class LolChampSelectLegacyPlayerStatus
    {
        [JsonProperty("currentLobbyStatus")]
        public LolChampSelectLegacyLobbyStatus CurrentLobbyStatus { get; set; }
        [JsonProperty("lastQueuedLobbyStatus")]
        public LolChampSelectLegacyLobbyStatus LastQueuedLobbyStatus { get; set; }
    }
}
