//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    public enum LolClubsClubPermission
    {
        INVITE,
        PROMOTE,
        DEMOTE,
        KICK_MEMBER,
        KICK_OFFICER,
        OWNERSHIP_TRANSFER,
        NOMINATE,
        SET_MOTD,
        SET_DESCRIPTION,
    }
}
