//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    [JsonObject]
    public class LolGameSessionGameSessionReconnect
    {
        [JsonProperty("gameInfo")]
        public LolGameSessionGameSessionGameInfo GameInfo { get; set; }
        [JsonProperty("playerReconnectInfo")]
        public LolGameSessionGameSessionPlayerReconnectInfo PlayerReconnectInfo { get; set; }
    }
}
