//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    public enum LolInventoryLoyaltyStatus
    {
        LEGACY,
        REWARDS_GRANT,
        EXPIRY,
        CHANGE,
        REVOKE,
        DISABLED,
    }
}
