//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    [JsonObject]
    public class LolLoadoutsLoadout
    {
        [JsonProperty("id")]
        public int Id { get; set; }
        [JsonProperty("items")]
        public object Items { get; set; }
        [JsonProperty("name")]
        public string Name { get; set; }
    }
}
