//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    [JsonObject]
    public class LolLobbyTeamBuilderCeremonyV1
    {
        [JsonProperty("duration")]
        public long Duration { get; set; }
        [JsonProperty("name")]
        public string Name { get; set; }
    }
}
