//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    [JsonObject]
    public class LolLoginLcdsResponse
    {
        [JsonProperty("body")]
        public object Body { get; set; }
        [JsonProperty("typeName")]
        public string TypeName { get; set; }
    }
}
