//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    [JsonObject]
    public class LolLoyaltyLoyaltyStatusNotification
    {
        [JsonProperty("rewards")]
        public LolLoyaltyLoyaltyRewards Rewards { get; set; }
        [JsonProperty("status")]
        public LolLoyaltyLoyaltyStatus Status { get; set; }
    }
}
