//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    [JsonObject]
    public class LolLoadoutsGameflowSession
    {
        [JsonProperty("gameData")]
        public LolLoadoutsGameflowGameData GameData { get; set; }
        [JsonProperty("phase")]
        public LolLoadoutsGameflowPhase Phase { get; set; }
    }
}
