//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    [JsonObject]
    public class LolMatchHistoryRecentlyPlayedSummoner
    {
        [JsonProperty("championId")]
        public long ChampionId { get; set; }
        [JsonProperty("gameCreationDate")]
        public string GameCreationDate { get; set; }
        [JsonProperty("gameId")]
        public long GameId { get; set; }
        [JsonProperty("summonerId")]
        public long SummonerId { get; set; }
        [JsonProperty("summonerName")]
        public string SummonerName { get; set; }
        [JsonProperty("teamId")]
        public long TeamId { get; set; }
    }
}
