//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    [JsonObject]
    public class LolMatchHistoryMatchHistoryTimelineFrame
    {
        [JsonProperty("events")]
        public LolMatchHistoryMatchHistoryEvent[] Events { get; set; }
        [JsonProperty("participantFrames")]
        public object ParticipantFrames { get; set; }
        [JsonProperty("timestamp")]
        public long Timestamp { get; set; }
    }
}
