//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    [JsonObject]
    public class LolNpeTutorialPathLobbyDto
    {
        [JsonProperty("gameConfig")]
        public LolNpeTutorialPathLobbyGameConfigDto GameConfig { get; set; }
        [JsonProperty("partyId")]
        public string PartyId { get; set; }
    }
}
