//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    public enum LolPremadeVoicePartyMemberRoleEnum
    {
        LEADER,
        MEMBER,
        INVITED,
        HOLD,
        KICKED,
        DECLINED,
    }
}
