//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    [JsonObject]
    public class LolPersonalizedOffersOfferData
    {
        [JsonProperty("offers")]
        public LolPersonalizedOffersOffer[] Offers { get; set; }
        [JsonProperty("promotion")]
        public LolPersonalizedOffersPromotion Promotion { get; set; }
    }
}
