//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    [JsonObject]
    public class LolPerksPerkSubStyleBonusResource
    {
        [JsonProperty("perkId")]
        public int PerkId { get; set; }
        [JsonProperty("styleId")]
        public int StyleId { get; set; }
    }
}
