//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    public enum LolPerksChampSelectTradeState
    {
        AVAILABLE,
        BUSY,
        INVALID,
        RECEIVED,
        SENT,
    }
}
