//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    [JsonObject]
    public class LolPerksPerkBook
    {
        [JsonProperty("currentPageId")]
        public int CurrentPageId { get; set; }
        [JsonProperty("pages")]
        public LolPerksPerkPageResource[] Pages { get; set; }
    }
}
