//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    public enum LolRecommendationsItemType
    {
        CHAMPION,
        CHAMPION_SKIN,
        BUNDLES,
        HEXTECH_CRAFTING,
        SUMMONER_ICON,
        WARD_SKIN,
        EMOTE,
    }
}
