//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    [JsonObject]
    public class LolRankedRankedReward
    {
        [JsonProperty("itemId")]
        public string ItemId { get; set; }
        [JsonProperty("pointsRequired")]
        public int PointsRequired { get; set; }
    }
}
