//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    public enum LolSummonerLoginSessionStates
    {
        IN_PROGRESS,
        SUCCEEDED,
        LOGGING_OUT,
        ERROR,
    }
}
