//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    [JsonObject]
    public class LolSummonerRerollDataBagForClientV1
    {
        [JsonProperty("maximumRerolls")]
        public int MaximumRerolls { get; set; }
        [JsonProperty("pointCostOfReroll")]
        public long PointCostOfReroll { get; set; }
        [JsonProperty("pointsGainedLastGame")]
        public long PointsGainedLastGame { get; set; }
        [JsonProperty("pointsUntilNextReroll")]
        public long PointsUntilNextReroll { get; set; }
        [JsonProperty("queueId")]
        public long QueueId { get; set; }
        [JsonProperty("rerollCount")]
        public int RerollCount { get; set; }
        [JsonProperty("totalPoints")]
        public long TotalPoints { get; set; }
    }
}
