//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    [JsonObject]
    public class LolSuggestedPlayersSuggestedPlayersKudoedPlayer
    {
        [JsonProperty("kudoedSummonerId")]
        public long KudoedSummonerId { get; set; }
        [JsonProperty("kudoedSummonerName")]
        public string KudoedSummonerName { get; set; }
    }
}
