//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    [JsonObject]
    public class LolSuggestedPlayersEndOfGameStats
    {
        [JsonProperty("teams")]
        public LolSuggestedPlayersEndOfGameTeam[] Teams { get; set; }
    }
}
