//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    [JsonObject]
    public class LolServiceStatusLoginDataPacket
    {
        [JsonProperty("broadcastNotification")]
        public LolServiceStatusBroadcastNotification BroadcastNotification { get; set; }
    }
}
