//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    [JsonObject]
    public class MatchmakingLcdsSummoner
    {
        [JsonProperty("name")]
        public string Name { get; set; }
        [JsonProperty("sumId")]
        public long SumId { get; set; }
    }
}
