//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    [JsonObject]
    public class MatchmakingLcdsSearchingForMatchNotification
    {
        [JsonProperty("joinedQueues")]
        public MatchmakingLcdsQueueInfo[] JoinedQueues { get; set; }
        [JsonProperty("playerJoinFailures")]
        public object[] PlayerJoinFailures { get; set; }
    }
}
