//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    [JsonObject]
    public class MetricMetadataHipchatNotification
    {
        [JsonProperty("roomid")]
        public string Roomid { get; set; }
        [JsonProperty("tags")]
        public string Tags { get; set; }
    }
}
