//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    public enum PatcherNotificationId
    {
        UnspecifiedError,
        ConnectionError,
        MissingFilesError,
        FailedToWriteError,
        WillRestoreClientBackupOnRestart,
        DidRestoreClientBackup,
    }
}
