//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    [JsonObject]
    public class RecofrienderContactPaginationResource
    {
        [JsonProperty("cached")]
        public long Cached { get; set; }
        [JsonProperty("count")]
        public long Count { get; set; }
        [JsonProperty("limit")]
        public long Limit { get; set; }
        [JsonProperty("more")]
        public bool More { get; set; }
        [JsonProperty("start")]
        public long Start { get; set; }
        [JsonProperty("total")]
        public long Total { get; set; }
    }
}
