//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    [JsonObject]
    public class RiotMessagingServiceEntitlementsToken
    {
        [JsonProperty("accessToken")]
        public string AccessToken { get; set; }
        [JsonProperty("entitlements")]
        public string[] Entitlements { get; set; }
        [JsonProperty("issuer")]
        public string Issuer { get; set; }
        [JsonProperty("subject")]
        public string Subject { get; set; }
        [JsonProperty("token")]
        public string Token { get; set; }
    }
}
