//Auto-generated by https://github.com/pipe01/lcu-api-generator
using Newtonsoft.Json;

namespace GlassLCU.API.Models
{
    [JsonObject]
    public class RosterWithdraw
    {
        [JsonProperty("declineWithdrawMembers")]
        public long[] DeclineWithdrawMembers { get; set; }
        [JsonProperty("gameStartBufferMs")]
        public long GameStartBufferMs { get; set; }
        [JsonProperty("initVoteMember")]
        public long InitVoteMember { get; set; }
        [JsonProperty("initVoteTime")]
        public long InitVoteTime { get; set; }
        [JsonProperty("lockoutTimeMs")]
        public long LockoutTimeMs { get; set; }
        [JsonProperty("voteTimeoutMs")]
        public long VoteTimeoutMs { get; set; }
        [JsonProperty("voteWithdrawMembers")]
        public long[] VoteWithdrawMembers { get; set; }
    }
}
